# These are supported funding model platforms
# 取消注释并填入对应平台用户名即可启用赞助按钮

# github: [your-github-username]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
# custom: ["https://your-link.com"]
