"""
CRUD Generator — 迁移文件清理工具

按模块名查找和删除 migrations/versions/crud/ 中的迁移文件。
通过解析文件头注释中的模块标识来匹配：
  Auto-generated by CRUD Generator for module '{module}'.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from app.core.logging import LogManager

logger = LogManager.get_logger("app")

# 匹配迁移文件中的模块标识注释
_MODULE_PATTERN = re.compile(
    r"Auto-generated by CRUD Generator for module '([^']+)'"
)

# CRUD 迁移子目录
_CRUD_MIGRATION_DIR = "migrations/versions/crud"


def find_crud_migrations(
    project_root: str | Path,
    module_name: str,
) -> list[str]:
    """
    查找指定模块的所有 CRUD 迁移文件

    扫描 migrations/versions/crud/ 目录下的 .py 文件，
    通过文件内容中的模块标识注释来匹配。

    Args:
        project_root: 项目根目录（backend/）
        module_name: CRUD 模块名（kebab-case）

    Returns:
        匹配的迁移文件相对路径列表
    """
    root = Path(project_root)
    crud_dir = root / _CRUD_MIGRATION_DIR

    if not crud_dir.is_dir():
        return []

    matched: list[str] = []

    for py_file in sorted(crud_dir.glob("*.py")):
        if py_file.name.startswith("__"):
            continue
        try:
            content = py_file.read_text(encoding="utf-8")
            match = _MODULE_PATTERN.search(content)
            if match and match.group(1) == module_name:
                rel_path = str(py_file.relative_to(root)).replace("\\", "/")
                matched.append(rel_path)
        except OSError:
            continue

    return matched


def remove_crud_migrations(
    project_root: str | Path,
    module_name: str,
) -> dict[str, Any]:
    """
    删除指定模块的所有 CRUD 迁移文件

    Args:
        project_root: 项目根目录（backend/）
        module_name: CRUD 模块名（kebab-case）

    Returns:
        {"deleted": int, "paths": list[str], "errors": list[str]}
    """
    root = Path(project_root)
    files = find_crud_migrations(root, module_name)

    deleted = 0
    paths: list[str] = []
    errors: list[str] = []

    for rel_path in files:
        abs_path = root / rel_path
        try:
            abs_path.unlink()
            deleted += 1
            paths.append(rel_path)
            logger.info("Deleted CRUD migration: %s", rel_path)
        except OSError as exc:
            errors.append(f"{rel_path}: {exc}")
            logger.warning("Failed to delete migration %s: %s", rel_path, exc)

    return {"deleted": deleted, "paths": paths, "errors": errors}


__all__ = ["find_crud_migrations", "remove_crud_migrations"]
