"""Admin APIs for storage billing plugin. / 对象存储对账计费插件管理端接口。"""

from __future__ import annotations

from fastapi import Request

from ..schemas import (
    CreateStorageTenantBindingRequestSchema,
    UpdateProviderProfilesRequestSchema,
    UpdateStorageTenantBindingRequestSchema,
)
from ..services import (
    StorageBillingBindingService,
    StorageBillingProviderProfileService,
)
from ..services.reconciliation_service import (
    StorageBillingOverviewService,
    StorageBillingReconciliationService,
)


async def get_overview(request: Request, ctx) -> dict:
    """Return plugin overview. / 返回插件概览。"""
    _ = request
    service = StorageBillingOverviewService.from_context(ctx)
    return await service.build_admin_overview()


async def list_provider_profiles(request: Request, ctx) -> dict:
    """List provider profiles. / 列出提供方配置。"""
    _ = request
    service = StorageBillingProviderProfileService.from_context(ctx)
    return await service.list_provider_profiles()


async def save_provider_profiles(request: Request, ctx) -> dict:
    """Save provider profiles. / 保存提供方配置。"""
    body = await request.json()
    payload = UpdateProviderProfilesRequestSchema.model_validate(body)
    service = StorageBillingProviderProfileService.from_context(ctx)
    return await service.save_provider_profiles(payload.model_dump(exclude_none=True))


async def validate_provider_profile(request: Request, ctx) -> dict:
    """Validate a provider profile. / 校验单个提供方配置。"""
    provider_code = str(request.path_params["provider"]).strip()
    body = await request.json() if request.headers.get("content-type", "").startswith("application/json") else {}
    raw_profile = body.get("profile") if isinstance(body, dict) else {}
    service = StorageBillingProviderProfileService.from_context(ctx)
    return await service.validate_provider_profile(
        provider_code,
        dict(raw_profile or {}),
    )


async def list_bindings(request: Request, ctx) -> dict:
    """List tenant bindings. / 列出租户绑定。"""
    service = StorageBillingBindingService.from_context(ctx)
    return await service.list_bindings(request)


async def create_binding(request: Request, ctx) -> dict:
    """Create tenant binding. / 创建租户绑定。"""
    body = await request.json()
    payload = CreateStorageTenantBindingRequestSchema.model_validate(body)
    service = StorageBillingBindingService.from_context(ctx)
    return await service.create_binding(payload.model_dump(exclude_none=True))


async def update_binding(request: Request, ctx) -> dict:
    """Update tenant binding. / 更新租户绑定。"""
    binding_id = int(request.path_params["binding_id"])
    body = await request.json()
    payload = UpdateStorageTenantBindingRequestSchema.model_validate(body)
    service = StorageBillingBindingService.from_context(ctx)
    return await service.update_binding(
        binding_id,
        payload.model_dump(exclude_none=True),
    )


async def validate_binding(request: Request, ctx) -> dict:
    """Validate tenant binding. / 校验租户绑定。"""
    binding_id = int(request.path_params["binding_id"])
    service = StorageBillingBindingService.from_context(ctx)
    return await service.validate_binding(binding_id)


async def list_reconciliation_runs(request: Request, ctx) -> dict:
    """List reconciliation runs. / 列出对账任务。"""
    raw_limit = request.query_params.get("limit", "20")
    try:
        limit = int(raw_limit)
    except (TypeError, ValueError):
        limit = 20
    service = StorageBillingReconciliationService.from_context(ctx)
    return await service.list_runs(limit=limit)


async def get_reconciliation_run(request: Request, ctx) -> dict:
    """Get reconciliation run detail. / 获取单次对账详情。"""
    run_id = int(request.path_params["run_id"])
    service = StorageBillingReconciliationService.from_context(ctx)
    return await service.get_run_detail(run_id)


async def list_reconciliation_run_charges(request: Request, ctx) -> dict:
    """List charge rows generated by a reconciliation run. / 列出任务生成的费用明细。"""
    run_id = int(request.path_params["run_id"])
    provider_code = request.query_params.get("provider_code")
    raw_source_id = request.query_params.get("source_id")
    raw_tenant_id = request.query_params.get("tenant_id")

    source_id = int(raw_source_id) if raw_source_id and raw_source_id.isdigit() else None
    tenant_id = int(raw_tenant_id) if raw_tenant_id and raw_tenant_id.isdigit() else None

    service = StorageBillingReconciliationService.from_context(ctx)
    return await service.list_run_charges(
        run_id=run_id,
        provider_code=provider_code,
        source_id=source_id,
        tenant_id=tenant_id,
    )


async def export_reconciliation_run_charges(request: Request, ctx):
    """Export charge rows for a reconciliation run. / 导出单次任务费用明细。"""
    run_id = int(request.path_params["run_id"])
    provider_code = request.query_params.get("provider_code")
    raw_source_id = request.query_params.get("source_id")
    raw_tenant_id = request.query_params.get("tenant_id")

    source_id = int(raw_source_id) if raw_source_id and raw_source_id.isdigit() else None
    tenant_id = int(raw_tenant_id) if raw_tenant_id and raw_tenant_id.isdigit() else None

    service = StorageBillingReconciliationService.from_context(ctx)
    return await service.export_run_charges_csv(
        run_id=run_id,
        provider_code=provider_code,
        source_id=source_id,
        tenant_id=tenant_id,
    )


async def run_reconciliation(request: Request, ctx) -> dict:
    """Trigger a persisted reconciliation run. / 触发持久化对账任务。"""
    body = await request.json() if request.headers.get("content-type", "").startswith("application/json") else {}
    service = StorageBillingReconciliationService.from_context(ctx)
    return await service.trigger_manual_run(body if isinstance(body, dict) else {})


async def run_qiniu_monthly_settlement(request: Request, ctx) -> dict:
    """Trigger a persisted Qiniu monthly settlement run. / 触发七牛云月结账单拉取。"""
    body = await request.json() if request.headers.get("content-type", "").startswith("application/json") else {}
    service = StorageBillingReconciliationService.from_context(ctx)
    return await service.trigger_qiniu_monthly_settlement(
        body if isinstance(body, dict) else {}
    )
