/**
 * Platform role management API / 平台角色管理 API
 * Backend: /admin/roles/*
 */
import type { SelectOption, SelectResponse } from '#/types';
import type { ApiRequestOptions } from '#/utils/request';

import { requestClient } from '#/utils/request';

// ============================================================
// Type definitions / 类型定义
// ============================================================

/** Node type / 节点类型 */
export type RoleType = 'department' | 'position' | 'role';

/** Create role request / 创建角色请求 */
export interface RoleCreateRequest {
  code?: string; // Generated by backend, no need for frontend input / 后端生成
  name: string;
  description?: null | string;
  is_active?: boolean;
  sort_order?: number;
  parent_id?: null | number;
  permission_ids?: number[];
  /** Node type: department/position/role, default role / 节点类型 */
  type?: RoleType;
  /** Allow adding members, default true / 是否允许添加成员 */
  allow_members?: boolean;
}

/** Update role request / 更新角色请求 */
export interface RoleUpdateRequest {
  name?: null | string;
  description?: null | string;
  is_active?: boolean | null;
  sort_order?: null | number;
  permission_ids?: null | number[];
  /** Node type: department/position/role / 节点类型 */
  type?: null | RoleType;
  /** Allow adding members / 是否允许添加成员 */
  allow_members?: boolean | null;
  /** Leader ID / 负责人 ID */
  leader_id?: null | number;
}

/** Assign permissions request / 分配权限请求 */
export interface RolePermissionsRequest {
  permission_ids: number[];
}

/** Permission basic info / 权限基本信息 */
export interface PermissionBasicInfo {
  id: number;
  code: string;
  name: string;
  type: string;
}

/** Leader basic info / 负责人基本信息 */
export interface LeaderBasicInfo {
  id: number;
  username: string;
  real_name?: string;
  avatar?: string;
}

/** Role info (backend raw snake_case) / 角色信息（后端原始） */
export interface RoleInfoRaw {
  id: number;
  code: string;
  name: string;
  description?: string;
  is_active: boolean;
  sort_order: number;
  permissions?: PermissionBasicInfo[];
  permission_ids?: number[]; // Permission IDs returned by role detail / 角色详情返回的权限 ID
  permissions_count?: number;
  created_at: string;
  updated_at?: string;
  // Organization structure extended fields / 组织架构扩展字段
  type?: RoleType;
  level?: number;
  has_children?: boolean;
  allow_members?: boolean;
  member_count?: number;
  leader_id?: null | number;
  leader?: LeaderBasicInfo | null;
  parent_id?: null | number;
  children?: RoleInfoRaw[];
}

/** Role info (frontend camelCase) / 角色信息（前端） */
export interface RoleInfo {
  id: number;
  code: string;
  name: string;
  description?: string;
  isActive: boolean;
  sortOrder: number;
  parentId?: null | number;
  permissions?: PermissionBasicInfo[];
  permissionIds?: number[]; // Permission IDs returned by role detail / 角色详情权限 ID
  permissionsCount?: number;
  children?: RoleInfo[];
  createdAt: string;
  updatedAt?: string;
  // Organization structure extended fields / 组织架构扩展字段
  type?: RoleType;
  level?: number;
  hasChildren?: boolean;
  allowMembers?: boolean;
  memberCount?: number;
  leaderId?: null | number;
  leader?: LeaderBasicInfo | null;
}

/** Move role request / 移动角色请求 */
export interface RoleMoveRequest {
  new_parent_id: null | number;
}

// ============================================================
// Transform functions / 转换函数
// ============================================================

/** Convert backend snake_case to frontend camelCase / 将后端转换为前端格式 */
function transformRoleInfo(raw: RoleInfoRaw): RoleInfo {
  return {
    id: raw.id,
    code: raw.code,
    name: raw.name,
    description: raw.description,
    isActive: raw.is_active,
    sortOrder: raw.sort_order,
    parentId: raw.parent_id,
    permissions: raw.permissions,
    permissionIds: raw.permission_ids,
    permissionsCount:
      raw.permissions_count ??
      raw.permission_ids?.length ??
      (raw.permissions ? raw.permissions.length : 0),
    children: raw.children?.map((item: RoleInfoRaw) => transformRoleInfo(item)),
    createdAt: raw.created_at,
    updatedAt: raw.updated_at,
    // Organization structure extended fields / 组织架构扩展字段
    type: raw.type,
    level: raw.level,
    hasChildren: raw.has_children,
    allowMembers: raw.allow_members,
    memberCount: raw.member_count,
    leaderId: raw.leader_id,
    leader: raw.leader,
  };
}

// ============================================================
// API functions / API 接口
// ============================================================

const API_PREFIX = '/admin/roles';

/**
 * Get role list / 获取角色列表
 * GET /admin/roles
 * Note: Role list is not paginated, returns all
 */
export async function getRoleListApi(
  options?: ApiRequestOptions,
): Promise<RoleInfo[]> {
  const response = await requestClient.get<RoleInfoRaw[]>(API_PREFIX, options);
  return response.map((item) => transformRoleInfo(item));
}

/**
 * Get role detail / 获取角色详情
 * GET /admin/roles/{role_id}
 */
export async function getRoleDetailApi(
  roleId: number,
  options?: ApiRequestOptions,
): Promise<RoleInfo> {
  const raw = await requestClient.get<RoleInfoRaw>(
    `${API_PREFIX}/${roleId}`,
    options,
  );
  return transformRoleInfo(raw);
}

/**
 * Create role / 创建角色
 * POST /admin/roles
 */
export async function createRoleApi(
  data: RoleCreateRequest,
  options?: ApiRequestOptions,
): Promise<RoleInfo> {
  const raw = await requestClient.post<RoleInfoRaw>(API_PREFIX, data, options);
  return transformRoleInfo(raw);
}

/**
 * Update role / 更新角色
 * PUT /admin/roles/{role_id}
 */
export async function updateRoleApi(
  roleId: number,
  data: RoleUpdateRequest,
  options?: ApiRequestOptions,
): Promise<RoleInfo> {
  const raw = await requestClient.put<RoleInfoRaw>(
    `${API_PREFIX}/${roleId}`,
    data,
    options,
  );
  return transformRoleInfo(raw);
}

/**
 * Delete role / 删除角色
 * DELETE /admin/roles/{role_id}
 */
export async function deleteRoleApi(
  roleId: number,
  options?: ApiRequestOptions,
): Promise<void> {
  await requestClient.delete(`${API_PREFIX}/${roleId}`, options);
}

/**
 * Assign role permissions / 分配角色权限
 * PUT /admin/roles/{role_id}/permissions
 */
export async function assignRolePermissionsApi(
  roleId: number,
  data: RolePermissionsRequest,
  options?: ApiRequestOptions,
): Promise<RoleInfo> {
  const raw = await requestClient.put<RoleInfoRaw>(
    `${API_PREFIX}/${roleId}/permissions`,
    data,
    options,
  );
  return transformRoleInfo(raw);
}

/**
 * Get role tree / 获取角色树
 * GET /admin/roles/tree
 * Returns tree structure with hierarchy
 */
export async function getRoleTreeApi(
  options?: ApiRequestOptions,
): Promise<RoleInfo[]> {
  const response = await requestClient.get<RoleInfoRaw[]>(
    `${API_PREFIX}/tree`,
    options,
  );
  return response.map((item) => transformRoleInfo(item));
}

/**
 * Get child roles / 获取子角色
 * GET /admin/roles/{role_id}/children
 */
export async function getRoleChildrenApi(
  roleId: number,
  options?: ApiRequestOptions,
): Promise<RoleInfo[]> {
  const response = await requestClient.get<RoleInfoRaw[]>(
    `${API_PREFIX}/${roleId}/children`,
    options,
  );
  return response.map((item) => transformRoleInfo(item));
}

/**
 * Move role / 移动角色
 * PUT /admin/roles/{role_id}/move
 */
export async function moveRoleApi(
  roleId: number,
  data: RoleMoveRequest,
  options?: ApiRequestOptions,
): Promise<RoleInfo> {
  const raw = await requestClient.put<RoleInfoRaw>(
    `${API_PREFIX}/${roleId}/move`,
    data,
    options,
  );
  return transformRoleInfo(raw);
}

/**
 * Get role select options / 获取角色下拉选项
 * GET /admin/roles/select
 * For dropdown selectors, returns simplified option list
 */
export async function getRoleSelectApi(
  params?: Record<string, unknown>,
  options?: ApiRequestOptions,
): Promise<SelectResponse> {
  const response = await requestClient.get<SelectOption[]>(
    `${API_PREFIX}/select`,
    { params, ...options },
  );
  return { items: response };
}
