import type { SelectResponse } from '#/api/shared/types';
/**
 * Tenant management API / 企业管理 API
 * Backend: /admin/tenants/*
 */
import type { ApiRequestOptions } from '#/utils/request';

import { requestClient } from '#/utils/request';

// ============================================================
// Type definitions / 类型定义
// ============================================================

/** Tenant list query params / 企业列表查询参数 */
export type TenantListParams = Record<string, unknown>;

/** Create tenant request / 创建企业请求 */
export interface TenantCreateRequest {
  /** Tenant code (optional, auto-generated by backend) / 企业编码 */
  code?: string;
  name: string;
  contact_name?: null | string;
  contact_phone?: null | string;
  contact_email?: null | string;
  quota?: null | Record<string, any>;
  expires_at?: null | string;
  remark?: null | string;
}

/** Update tenant request / 更新企业请求 */
export interface TenantUpdateRequest {
  name?: null | string;
  contact_name?: null | string;
  contact_phone?: null | string;
  contact_email?: null | string;
  quota?: null | Record<string, any>;
  expires_at?: null | string;
  remark?: null | string;
}

/** Toggle status request / 切换状态请求 */
export interface TenantStatusRequest {
  is_active: boolean;
}

/** Domain brief info (backend raw format) / 域名简要信息（后端原始格式） */
export interface TenantDomainBriefRaw {
  id: number;
  tenant_id: number;
  domain: string;
  domain_type?: 'custom' | 'default';
  is_verified: boolean;
  verified_at: null | string;
  is_primary: boolean;
  ssl_status: 'active' | 'failed' | 'pending';
  ssl_expires_at: null | string;
  cname_target: null | string;
  remark: null | string;
  created_at: string;
  updated_at: string;
}

/** Domain brief info (frontend format) / 域名简要信息（前端格式） */
export interface TenantDomainBrief {
  id: number;
  domain: string;
  domainType: 'custom' | 'default';
  isPrimary: boolean;
  verificationStatus: 'pending' | 'verified';
  sslStatus: 'active' | 'failed' | 'pending';
  cnameTarget?: null | string;
}

/** Plan brief info (backend raw format) / 套餐简要信息（后端原始格式） */
export interface TenantPlanBriefRaw {
  id: number;
  code: string;
  name: string;
}

/** Plan brief info (frontend format) / 套餐简要信息（前端格式） */
export interface TenantPlanBrief {
  id: number;
  code: string;
  name: string;
}

/** Tenant info (backend raw snake_case) / 企业信息（后端原始格式） */
export interface TenantInfoRaw {
  id: number;
  code: string;
  name: string;
  contact_name?: string;
  contact_phone?: string;
  contact_email?: string;
  plan_id?: null | number;
  plan_info?: null | TenantPlanBriefRaw;
  quota?: Record<string, any>;
  is_active: boolean;
  expires_at?: string;
  remark?: string;
  created_at: string;
  updated_at?: string;
  // Domain info / 域名信息
  primary_domain?: null | TenantDomainBriefRaw;
  domain_count?: number;
  domains?: TenantDomainBriefRaw[];
}

/** Tenant info (frontend camelCase) / 企业信息（前端格式） */
export interface TenantInfo {
  id: number;
  code: string;
  name: string;
  contactName?: string;
  contactPhone?: string;
  contactEmail?: string;
  planId?: null | number;
  planInfo?: null | TenantPlanBrief;
  quota?: Record<string, any>;
  isActive: boolean;
  expiresAt?: string;
  remark?: string;
  createdAt: string;
  updatedAt?: string;
  // Domain info / 域名信息
  primaryDomain?: null | TenantDomainBrief;
  domainCount?: number;
  domains?: TenantDomainBrief[];
}

/** Paginated list response / 分页列表响应 */
export interface TenantListResponse {
  items: TenantInfo[];
  total: number;
  page: number;
  page_size: number;
}

// ============================================================
// Transform functions / 转换函数
// ============================================================

/** Transform domain brief info / 转换域名简要信息 */
function transformDomainBrief(raw: TenantDomainBriefRaw): TenantDomainBrief {
  return {
    id: raw.id,
    domain: raw.domain,
    domainType: raw.domain_type === 'default' ? 'default' : 'custom',
    isPrimary: raw.is_primary,
    verificationStatus: raw.is_verified ? 'verified' : 'pending',
    sslStatus: raw.ssl_status,
    cnameTarget: raw.cname_target,
  };
}

/** Convert backend snake_case to frontend camelCase / 将后端转换为前端格式 */
function transformTenantInfo(raw: TenantInfoRaw): TenantInfo {
  return {
    id: raw.id,
    code: raw.code,
    name: raw.name,
    contactName: raw.contact_name,
    contactPhone: raw.contact_phone,
    contactEmail: raw.contact_email,
    planId: raw.plan_id,
    planInfo: raw.plan_info || null,
    quota: raw.quota,
    isActive: raw.is_active,
    expiresAt: raw.expires_at,
    remark: raw.remark,
    createdAt: raw.created_at,
    updatedAt: raw.updated_at,
    // Domain info / 域名信息
    primaryDomain: raw.primary_domain
      ? transformDomainBrief(raw.primary_domain)
      : null,
    domainCount: raw.domain_count,
    domains: raw.domains?.map((d) => transformDomainBrief(d)),
  };
}

// ============================================================
// API functions / API 接口
// ============================================================

const API_PREFIX = '/admin/tenants';

/** Tenant select option result / 企业下拉选项结果 */
export interface TenantSelectOption {
  label: string;
  value: number;
  extra?: {
    code?: string;
    isActive?: boolean;
  };
}

/**
 * Get tenant select options / 获取企业下拉选项
 * GET /admin/tenants/select
 *
 * Permission: tenant:select
 */
export async function getTenantSelectApi(
  params?: Record<string, unknown>,
  options?: ApiRequestOptions,
): Promise<{ items: TenantSelectOption[] }> {
  return requestClient.get<{ items: TenantSelectOption[] }>(
    `${API_PREFIX}/select`,
    { params, ...options },
  );
}

/**
 * Get tenant list / 获取企业列表
 * GET /admin/tenants
 */
export async function getTenantListApi(
  params?: TenantListParams,
  options?: ApiRequestOptions,
): Promise<TenantListResponse> {
  const response = await requestClient.get<{
    items: TenantInfoRaw[];
    page: number;
    page_size: number;
    total: number;
  }>(API_PREFIX, { params, ...options });

  return {
    items: response.items.map((item) => transformTenantInfo(item)),
    total: response.total,
    page: response.page,
    page_size: response.page_size,
  };
}

/**
 * Get tenant detail / 获取企业详情
 * GET /admin/tenants/{tenant_id}
 */
export async function getTenantDetailApi(
  tenantId: number,
  options?: ApiRequestOptions,
): Promise<TenantInfo> {
  const raw = await requestClient.get<TenantInfoRaw>(
    `${API_PREFIX}/${tenantId}`,
    options,
  );
  return transformTenantInfo(raw);
}

/**
 * Create tenant / 创建企业
 * POST /admin/tenants
 */
export async function createTenantApi(
  data: TenantCreateRequest,
  options?: ApiRequestOptions,
): Promise<TenantInfo> {
  const raw = await requestClient.post<TenantInfoRaw>(
    API_PREFIX,
    data,
    options,
  );
  return transformTenantInfo(raw);
}

/**
 * Update tenant / 更新企业
 * PUT /admin/tenants/{tenant_id}
 */
export async function updateTenantApi(
  tenantId: number,
  data: TenantUpdateRequest,
  options?: ApiRequestOptions,
): Promise<TenantInfo> {
  const raw = await requestClient.put<TenantInfoRaw>(
    `${API_PREFIX}/${tenantId}`,
    data,
    options,
  );
  return transformTenantInfo(raw);
}

/**
 * Delete tenant / 删除企业
 * DELETE /admin/tenants/{tenant_id}
 */
export async function deleteTenantApi(
  tenantId: number,
  options?: ApiRequestOptions,
): Promise<void> {
  await requestClient.delete(`${API_PREFIX}/${tenantId}`, options);
}

/**
 * Toggle tenant status / 切换企业状态
 * PUT /admin/tenants/{tenant_id}/status
 */
export async function toggleTenantStatusApi(
  tenantId: number,
  data: TenantStatusRequest,
  options?: ApiRequestOptions,
): Promise<TenantInfo> {
  const raw = await requestClient.put<TenantInfoRaw>(
    `${API_PREFIX}/${tenantId}/status`,
    data,
    options,
  );
  return transformTenantInfo(raw);
}

/** Reset tenant admin password request / 重置企业管理员密码请求 */
export interface ResetTenantOwnerPasswordRequest {
  new_password: string;
}

/**
 * Reset tenant admin password / 重置企业管理员密码
 * PUT /admin/tenants/{tenant_id}/reset-owner-password
 */
export async function resetTenantOwnerPasswordApi(
  tenantId: number,
  data: ResetTenantOwnerPasswordRequest,
  options?: ApiRequestOptions,
): Promise<void> {
  await requestClient.put(
    `${API_PREFIX}/${tenantId}/reset-owner-password`,
    data,
    options,
  );
}

// ============================================================
// Impersonation / 一键登录相关
// ============================================================

/** Impersonation request / 一键登录请求 */
export interface TenantImpersonateRequest {
  role_id?: null | number;
}

/** Impersonation response / 一键登录响应 */
export interface TenantImpersonateResponse {
  impersonateToken: string;
  tenantCode: string;
  tenantName: string;
  expiresIn: number;
}

/** Backend raw response / 后端原始响应 */
interface TenantImpersonateResponseRaw {
  impersonate_token: string;
  tenant_code: string;
  tenant_name: string;
  expires_in: number;
}

/**
 * Impersonate tenant admin / 一键登录企业后台
 * POST /admin/tenants/{tenant_id}/impersonate
 * Generate impersonation token (60s expiry, one-time use)
 */
export async function tenantImpersonateApi(
  tenantId: number,
  data?: TenantImpersonateRequest,
  options?: ApiRequestOptions,
): Promise<TenantImpersonateResponse> {
  const raw = await requestClient.post<TenantImpersonateResponseRaw>(
    `${API_PREFIX}/${tenantId}/impersonate`,
    data || {},
    options,
  );
  return {
    impersonateToken: raw.impersonate_token,
    tenantCode: raw.tenant_code,
    tenantName: raw.tenant_name,
    expiresIn: raw.expires_in,
  };
}

// ============================================================
// Tenant admin management API / 企业管理员管理 API
// ============================================================

/** Tenant admin info / 企业管理员信息 */
export interface TenantAdminItem {
  id: number;
  username: string;
  email: string;
  nickname: null | string;
  avatar: null | string;
  ai_enabled: boolean;
  can_view_activity?: boolean;
  is_owner: boolean;
  is_active: boolean;
  org_node_id?: null | number;
  org_node_name?: null | string;
  role_name: null | string;
  role_id: null | number;
  last_login_at: null | string;
  last_login_ip: null | string;
  created_at: null | string;
}

export interface TenantAdminIdentitySelectExtra {
  avatar?: null | string;
  ai_enabled?: boolean;
  display_name?: null | string;
  display_role_name?: null | string;
  is_active?: boolean;
  is_leader?: boolean;
  is_owner?: boolean;
  nickname?: null | string;
  org_node_id?: null | number;
  org_node_name?: null | string;
  role_name?: null | string;
  user_type?: null | string;
  username?: null | string;
}

export interface TenantAdminIdentityDetail {
  avatar?: null | string;
  ai_enabled?: boolean;
  ai_unavailable_reason?: null | string;
  can_view_activity?: boolean;
  created_at?: null | string;
  display_name?: null | string;
  display_role_name?: null | string;
  effective_ai_enabled?: boolean;
  email?: null | string;
  id: number;
  is_active?: boolean;
  is_leader?: boolean;
  is_owner?: boolean;
  last_login_at?: null | string;
  last_login_ip?: null | string;
  nickname?: null | string;
  org_node_id?: null | number;
  org_node_name?: null | string;
  permission_role_id?: null | number;
  permission_role_name?: null | string;
  phone?: null | string;
  role_id?: null | number;
  role_name?: null | string;
  tenant_id?: null | number;
  updated_at?: null | string;
  user_type?: null | string;
  username?: null | string;
}

/** Create tenant admin request / 创建企业管理员请求 */
export interface TenantAdminCreateRequest {
  username: string;
  email: string;
  password: string;
  ai_enabled?: boolean;
  nickname?: string;
  role_id?: number;
}

/** Update tenant admin request / 更新企业管理员请求 */
export interface TenantAdminUpdateRequest {
  ai_enabled?: boolean;
  email?: string;
  nickname?: string;
  password?: string;
}

/**
 * Get tenant admin list / 获取企业管理员列表
 */
export async function getTenantAdminsApi(
  tenantId: number,
): Promise<TenantAdminItem[]> {
  const items = await requestClient.get<TenantAdminItem[]>(
    `${API_PREFIX}/${tenantId}/admins`,
  );
  return items.map((item) => ({
    ...item,
    ai_enabled: item.ai_enabled ?? true,
    can_view_activity: item.can_view_activity ?? false,
  }));
}

/**
 * Get tenant admin identity select options / 获取企业管理员身份下拉
 * GET /admin/tenants/{tenant_id}/admins/select
 */
export async function getTenantAdminIdentitySelectApi(
  tenantId: number,
  params?: Record<string, unknown>,
  options?: ApiRequestOptions,
): Promise<SelectResponse<TenantAdminIdentitySelectExtra>> {
  return requestClient.get<SelectResponse<TenantAdminIdentitySelectExtra>>(
    `${API_PREFIX}/${tenantId}/admins/select`,
    { params, ...options },
  );
}

/**
 * Get tenant admin identity detail / 获取企业管理员身份详情（平台端）
 * GET /admin/tenants/{tenant_id}/admins/{admin_id}
 */
export async function getTenantAdminDetailApi(
  tenantId: number,
  adminId: number,
  options?: ApiRequestOptions,
): Promise<TenantAdminIdentityDetail> {
  const detail = await requestClient.get<TenantAdminIdentityDetail>(
    `${API_PREFIX}/${tenantId}/admins/${adminId}`,
    options,
  );
  return {
    ...detail,
    ai_enabled: detail.ai_enabled ?? true,
  };
}

/**
 * Create tenant admin / 创建企业管理员
 */
export async function createTenantAdminApi(
  tenantId: number,
  data: TenantAdminCreateRequest,
): Promise<Record<string, unknown>> {
  return requestClient.post(`${API_PREFIX}/${tenantId}/admins`, data);
}

/**
 * Update tenant admin / 更新企业管理员
 */
export async function updateTenantAdminApi(
  tenantId: number,
  adminId: number,
  data: TenantAdminUpdateRequest,
): Promise<Record<string, unknown>> {
  return requestClient.put(`${API_PREFIX}/${tenantId}/admins/${adminId}`, data);
}

/**
 * Toggle tenant admin status / 切换企业管理员状态
 */
export async function toggleTenantAdminStatusApi(
  tenantId: number,
  adminId: number,
  isActive: boolean,
): Promise<Record<string, unknown>> {
  return requestClient.put(
    `${API_PREFIX}/${tenantId}/admins/${adminId}/status`,
    { is_active: isActive },
  );
}

/**
 * Force logout tenant admin / 强制下线企业管理员
 * POST /admin/tenants/{tenant_id}/admins/{admin_id}/force-logout
 */
export async function forceLogoutTenantAdminApi(
  tenantId: number,
  adminId: number,
  options?: ApiRequestOptions,
): Promise<void> {
  await requestClient.post(
    `${API_PREFIX}/${tenantId}/admins/${adminId}/force-logout`,
    {},
    options,
  );
}
