"""Read-model repair for trusted recovery-evidence answers.

The runtime owns the durable turn result. This module only hydrates historical
read payloads whose stored assistant text was generated by an older, overly
short recovery-evidence preview while successful fetch_url evidence is still
available in the canonical turn-flow evidence.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from app.ai.engine.recovery_tool_result_helpers import extract_fetch_url_user_preview
from app.ai.tools.types import ToolResult

LEGACY_RECOVERY_EVIDENCE_REPAIR_SCOPE = "legacy_fetch_url_preview_2026_05_04"
_LEGACY_RECOVERY_EVIDENCE_REPAIR_CONVERSATION_IDS = frozenset({2280, 2281})
_LEGACY_RECOVERY_EVIDENCE_REPAIR_BEFORE = datetime(
    2026, 5, 4, 9, 0, tzinfo=timezone.utc
)


def _as_dict(value: Any) -> dict[str, Any]:
    return dict(value) if isinstance(value, dict) else {}


def _as_str(value: Any) -> str:
    return str(value or "").strip()


def _as_int(value: Any) -> int | None:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return None
    return parsed if parsed > 0 else None


def _as_aware_datetime(value: Any) -> datetime | None:
    if isinstance(value, datetime):
        parsed = value
    elif isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        if text.endswith("Z"):
            text = f"{text[:-1]}+00:00"
        try:
            parsed = datetime.fromisoformat(text)
        except ValueError:
            return None
    else:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _conversation_id_from_message_payload(message: dict[str, Any]) -> int | None:
    metadata = _as_dict(message.get("metadata"))
    turn_record = _as_dict(metadata.get("turn_record"))
    runtime_turn_record = _as_dict(metadata.get("runtime_turn_record"))
    for candidate in (
        message.get("conversation_id"),
        metadata.get("conversation_id"),
        turn_record.get("conversation_id"),
        runtime_turn_record.get("conversation_id"),
    ):
        parsed = _as_int(candidate)
        if parsed is not None:
            return parsed
    return None


def _created_at_from_message_payload(message: dict[str, Any]) -> datetime | None:
    metadata = _as_dict(message.get("metadata"))
    for candidate in (
        message.get("created_at"),
        metadata.get("created_at"),
    ):
        parsed = _as_aware_datetime(candidate)
        if parsed is not None:
            return parsed
    return None


def _turn_flow_from_message_payload(message: dict[str, Any]) -> dict[str, Any]:
    metadata = _as_dict(message.get("metadata"))
    turn_record = _as_dict(metadata.get("turn_record"))
    turn_record_metadata = _as_dict(turn_record.get("metadata"))
    turn_record_diagnostics = _as_dict(turn_record_metadata.get("turn_diagnostics"))
    for candidate in (
        message.get("turn_flow"),
        metadata.get("turn_flow"),
        turn_record.get("turn_flow"),
        turn_record_metadata.get("turn_flow"),
        turn_record_diagnostics.get("turn_flow"),
    ):
        payload = _as_dict(candidate)
        if payload:
            return payload
    return {}


def _final_output_source_from_message_payload(message: dict[str, Any]) -> str:
    metadata = _as_dict(message.get("metadata"))
    context_diagnostics = _as_dict(metadata.get("context_diagnostics"))
    last_run_summary = _as_dict(metadata.get("last_run_summary"))
    turn_record = _as_dict(metadata.get("turn_record"))
    turn_record_metadata = _as_dict(turn_record.get("metadata"))
    turn_record_diagnostics = _as_dict(turn_record_metadata.get("turn_diagnostics"))
    for candidate in (
        metadata.get("final_output_source"),
        context_diagnostics.get("final_output_source"),
        last_run_summary.get("final_output_source"),
        turn_record.get("final_output_source"),
        turn_record_diagnostics.get("final_output_source"),
    ):
        text = _as_str(candidate)
        if text:
            return text
    return ""


def _explicit_legacy_repair_scope(message: dict[str, Any]) -> str:
    metadata = _as_dict(message.get("metadata"))
    for candidate in (
        message.get("legacy_recovery_evidence_repair_scope"),
        metadata.get("legacy_recovery_evidence_repair_scope"),
    ):
        scope = _as_str(candidate)
        if scope == LEGACY_RECOVERY_EVIDENCE_REPAIR_SCOPE:
            return scope
    return ""


def _legacy_recovery_evidence_repair_scope(message: dict[str, Any]) -> str:
    explicit_scope = _explicit_legacy_repair_scope(message)
    if explicit_scope:
        return explicit_scope
    conversation_id = _conversation_id_from_message_payload(message)
    if conversation_id not in _LEGACY_RECOVERY_EVIDENCE_REPAIR_CONVERSATION_IDS:
        return ""
    created_at = _created_at_from_message_payload(message)
    if created_at is None:
        return ""
    if created_at > _LEGACY_RECOVERY_EVIDENCE_REPAIR_BEFORE:
        return ""
    return LEGACY_RECOVERY_EVIDENCE_REPAIR_SCOPE


def _fetch_url_tool_result_from_evidence(item: dict[str, Any]) -> ToolResult | None:
    if _as_str(item.get("kind")) != "tool":
        return None
    tool_name = _as_str(
        item.get("tool_name")
        or item.get("source_ref")
        or item.get("title")
        or item.get("name")
    )
    if tool_name != "fetch_url":
        return None
    if _as_str(item.get("status")) not in {"", "success"}:
        return None
    summary_payload = _as_dict(item.get("summary_payload"))
    if summary_payload.get("ok") is False:
        return None
    return ToolResult(
        tool_call_id=_as_str(item.get("tool_call_id") or item.get("id") or "fetch_url"),
        name="fetch_url",
        success=True,
        output=_as_str(item.get("output")),
        summary=_as_str(item.get("snippet") or item.get("summary")),
        summary_payload=summary_payload,
    )


def _best_fetch_url_preview_from_turn_flow(turn_flow: dict[str, Any]) -> str:
    evidence = turn_flow.get("evidence")
    if not isinstance(evidence, list):
        return ""
    previews: list[str] = []
    for item in evidence:
        payload = _as_dict(item)
        if not payload:
            continue
        result = _fetch_url_tool_result_from_evidence(payload)
        if result is None:
            continue
        preview = extract_fetch_url_user_preview(result, max_length=1200)
        if preview and preview not in previews:
            previews.append(preview)
    if not previews:
        return ""
    return max(previews, key=len)


def _should_replace_recovery_answer(*, current_text: str, preview: str) -> bool:
    current = _as_str(current_text)
    replacement = _as_str(preview)
    if not replacement:
        return False
    if not current:
        return True
    if current == replacement:
        return False
    if len(replacement) < 120:
        return False
    return len(replacement) >= max(len(current) + 80, len(current) * 2)


def _patch_turn_flow_answer_card(
    turn_flow: dict[str, Any],
    *,
    preview: str,
) -> dict[str, Any]:
    patched = dict(turn_flow)
    answer_card = _as_dict(patched.get("answer_card"))
    answer_card["summary"] = preview
    sections = answer_card.get("sections")
    if isinstance(sections, list) and sections:
        next_sections: list[dict[str, Any]] = []
        replaced = False
        for item in sections:
            section = _as_dict(item)
            if not replaced:
                section["content"] = preview
                replaced = True
            next_sections.append(section)
        answer_card["sections"] = next_sections
    else:
        answer_card["sections"] = [{"title": "Answer", "content": preview}]
    patched["answer_card"] = answer_card
    return patched


def patch_recovery_evidence_answer_payload(
    message: dict[str, Any],
) -> dict[str, Any]:
    """Patch read payloads that have better successful fetch_url evidence.

    This is deliberately read-model only: callers pass a serialized message
    dict, and the returned dict is not written back to conversation_messages.
    """

    if not isinstance(message, dict) or _as_str(message.get("role")) != "assistant":
        return message
    if _final_output_source_from_message_payload(message) != "recovery_evidence":
        return message
    repair_scope = _legacy_recovery_evidence_repair_scope(message)
    turn_flow = _turn_flow_from_message_payload(message)
    if not turn_flow:
        return message
    preview = _best_fetch_url_preview_from_turn_flow(turn_flow)
    if not repair_scope:
        return message
    if not _should_replace_recovery_answer(
        current_text=_as_str(message.get("content")),
        preview=preview,
    ):
        return message

    patched = dict(message)
    patched["content"] = preview
    patched_turn_flow = _patch_turn_flow_answer_card(turn_flow, preview=preview)
    patched["turn_flow"] = patched_turn_flow
    metadata = _as_dict(patched.get("metadata"))
    metadata["turn_flow"] = patched_turn_flow
    metadata["recovery_evidence_read_model_repaired"] = True
    metadata["recovery_evidence_read_model_source"] = "fetch_url"
    metadata["recovery_evidence_read_model_repair_scope"] = repair_scope
    metadata["recovery_evidence_read_model_remove_after"] = (
        "Backfill conversations 2280/2281 or drop this legacy scope after "
        "2026-05-04 recovery-evidence preview incidents are no longer read."
    )
    patched["metadata"] = metadata
    return patched


__all__ = [
    "LEGACY_RECOVERY_EVIDENCE_REPAIR_SCOPE",
    "patch_recovery_evidence_answer_payload",
]
