/**
 * Captcha Extensible Architecture — Type Definitions
 * 验证码可扩展架构 — 类型定义
 */
import type { Component } from 'vue';

import type { CaptchaDifficulty } from '#/api/public/captcha';

/** Captcha endpoint type / 验证码端点类型 */
export type CaptchaEndpoint = 'admin' | 'tenant' | 'user';

/** Captcha provider type (built-in + plugin extensions) / 验证码提供商类型（内置 + 插件扩展） */
export type CaptchaProviderType =
  | 'hcaptcha'
  | 'image'
  | 'puzzle'
  | 'recaptcha'
  | 'turnstile'
  | (string & {});

/** Captcha action type / 验证码操作类型 */
export type CaptchaAction =
  | 'login'
  | 'register'
  | 'reset_password'
  | (string & {});

/** Captcha unified output result / 验证码统一输出结果 */
export interface CaptchaResult {
  /** Challenge ID (generated by backend) / 挑战 ID（后端生成） */
  challengeId: string;
  /** User-entered captcha code (image type) or token (third-party type) / 用户输入的验证码（图片类型）或 token（第三方类型） */
  captchaCode: string;
  /** Captcha provider type / 验证码提供商类型 */
  provider: CaptchaProviderType;
}

/** CaptchaProvider component Props / CaptchaProvider 组件 Props */
export interface CaptchaProviderProps {
  /** Endpoint identifier / 端点标识 */
  endpoint: CaptchaEndpoint;
  /** Captcha provider type (read from config, default 'image') / 验证码提供商类型（从配置读取，默认 'image'） */
  provider?: CaptchaProviderType;
  /** Difficulty level / 难度等级 */
  difficulty?: CaptchaDifficulty;
  /** Action type / 操作类型 */
  action?: CaptchaAction;
  /** Whether disabled / 是否禁用 */
  disabled?: boolean;
}

/** Interface that captcha adapter components must implement / 验证码适配器组件需要实现的接口 */
export interface CaptchaAdapterExpose {
  /** Refresh captcha / 刷新验证码 */
  refresh: () => void;
  /** Get verification result / 获取验证结果 */
  getResult: () => CaptchaResult | null;
}

/** Captcha registry entry / 验证码注册表项 */
export interface CaptchaRegistryEntry {
  /** Component / 组件 */
  component: Component;
  /** Display name (i18n key) / 显示名称（i18n key） */
  label?: string;
}
