/**
 * 图标选择器数据
 * 支持 Lucide 图标、项目自定义 SVG 图标和 iconfont 图标
 *
 * ============================================
 * 图标使用指南
 * ============================================
 *
 * 基本用法（在 Vue 组件中）:
 * ```vue
 * <script setup>
 * import { IconifyIcon } from '@vben/icons';
 * </script>
 *
 * <template>
 *   <IconifyIcon icon="lucide:user" class="size-5" />
 *   <IconifyIcon icon="svg:my-icon" class="size-5 text-primary" />
 * </template>
 * ```
 *
 * --------------------------------------------
 * 1. Lucide 图标 (推荐)
 * --------------------------------------------
 * - 直接使用，无需额外配置
 * - 图标列表: https://lucide.dev/icons
 * - 格式: icon="lucide:图标名"
 * - 示例: icon="lucide:user", icon="lucide:settings", icon="lucide:home"
 *
 * --------------------------------------------
 * 2. 项目自定义 SVG 图标
 * --------------------------------------------
 * 添加新图标步骤:
 *
 * 步骤 1: 将 SVG 文件放入 packages/icons/src/svg/icons/ 目录
 *         文件名使用 kebab-case 格式，如: my-custom-icon.svg
 *
 * 步骤 2: 在下面的 PROJECT_SVG_ICONS 数组中添加图标名称（不含 .svg 后缀）
 *         这样图标就会在图标选择器中显示
 *
 * 步骤 3 (可选): 如果需要在 TypeScript 中作为组件使用，
 *         可在 packages/icons/src/svg/index.ts 中注册:
 *         ```ts
 *         const SvgMyCustomIcon = createIconifyIcon('svg:my-custom-icon');
 *         export { SvgMyCustomIcon };
 *         ```
 *
 * 使用: icon="svg:my-custom-icon"
 *
 * --------------------------------------------
 * 3. iconfont 阿里图标库
 * --------------------------------------------
 * 使用 iconfont.cn 的图标:
 *
 * 步骤 1: 访问 https://www.iconfont.cn 创建项目
 * 步骤 2: 在图标库中搜索并添加需要的图标到项目
 * 步骤 3: 下载 SVG 格式（单个图标下载或批量下载）
 * 步骤 4: 将 SVG 文件放入 packages/icons/src/svg/icons/ 目录
 * 步骤 5: 在 PROJECT_SVG_ICONS 数组中添加图标名称
 *
 * 命名建议:
 * - 使用 kebab-case: my-icon.svg
 * - 按功能分类前缀: menu-home.svg, btn-submit.svg, icon-search.svg
 *
 * --------------------------------------------
 * 4. 其他 Iconify 图标集
 * --------------------------------------------
 * Iconify 支持 100+ 图标集，可以直接使用:
 *
 * - Material Design Icons: icon="mdi:account"
 * - Ant Design Icons: icon="ant-design:user-outlined"
 * - Carbon Icons: icon="carbon:user"
 * - Tabler Icons: icon="tabler:user"
 * - Feather Icons: icon="feather:user"
 * - Heroicons: icon="heroicons:user"
 *
 * 更多图标集: https://icon-sets.iconify.design
 *
 * 注意: 非 Lucide 图标集需要网络加载，首次使用时可能有延迟
 */

export interface IconCategory {
  name: string;
  label: string;
  /** 图标前缀，如 'lucide' 或 'svg' */
  prefix: string;
  icons: string[];
}

/**
 * 项目自定义 SVG 图标列表
 *
 * 来源目录: packages/icons/src/svg/icons/
 *
 * 添加新图标时，请同步更新此列表，以便在图标选择器中显示
 */
export const PROJECT_SVG_ICONS: string[] = [
  'avatar-1',
  'avatar-2',
  'avatar-3',
  'avatar-4',
  'download',
  'card',
  'bell',
  'cake',
  'antdv-logo',
  'github',
  'google',
  'qqchat',
  'wechat',
  'dingding',
  'tdesign-logo',
];

/**
 * Lucide 图标分类数据
 * 图标名称使用 lucide 原生格式（kebab-case）
 */
export const LUCIDE_CATEGORIES: IconCategory[] = [
  {
    name: 'arrows',
    label: '箭头',
    prefix: 'lucide',
    icons: [
      'arrow-up',
      'arrow-down',
      'arrow-left',
      'arrow-right',
      'arrow-up-left',
      'arrow-up-right',
      'arrow-down-left',
      'arrow-down-right',
      'chevron-up',
      'chevron-down',
      'chevron-left',
      'chevron-right',
      'chevrons-up',
      'chevrons-down',
      'chevrons-left',
      'chevrons-right',
      'chevrons-up-down',
      'chevrons-left-right',
      'move-up',
      'move-down',
      'move-left',
      'move-right',
      'corner-down-left',
      'corner-down-right',
      'corner-up-left',
      'corner-up-right',
      'corner-left-down',
      'corner-left-up',
      'corner-right-down',
      'corner-right-up',
      'arrow-big-up',
      'arrow-big-down',
      'arrow-big-left',
      'arrow-big-right',
      'undo',
      'redo',
      'undo-2',
      'redo-2',
      'refresh-cw',
      'refresh-ccw',
      'rotate-cw',
      'rotate-ccw',
      'repeat',
      'repeat-1',
      'repeat-2',
      'shuffle',
      'arrow-left-from-line',
      'arrow-right-from-line',
      'arrow-up-from-line',
      'arrow-down-from-line',
      'arrow-left-to-line',
      'arrow-right-to-line',
      'arrow-up-to-line',
      'arrow-down-to-line',
      'external-link',
      'log-in',
      'log-out',
      'import',
      'download',
      'upload',
    ],
  },
  {
    name: 'layout',
    label: '布局',
    prefix: 'lucide',
    icons: [
      'layout-dashboard',
      'layout-grid',
      'layout-list',
      'layout-template',
      'panel-left',
      'panel-right',
      'panel-top',
      'panel-bottom',
      'panel-left-close',
      'panel-right-close',
      'panel-top-close',
      'panel-bottom-close',
      'panel-left-open',
      'panel-right-open',
      'panel-top-open',
      'panel-bottom-open',
      'sidebar',
      'sidebar-close',
      'sidebar-open',
      'columns',
      'rows',
      'grip',
      'grip-horizontal',
      'grip-vertical',
      'square',
      'rectangle-horizontal',
      'rectangle-vertical',
      'maximize',
      'maximize-2',
      'minimize',
      'minimize-2',
      'fullscreen',
      'shrink',
      'expand',
      'fold-horizontal',
      'fold-vertical',
      'unfold-horizontal',
      'unfold-vertical',
    ],
  },
  {
    name: 'actions',
    label: '操作',
    prefix: 'lucide',
    icons: [
      'plus',
      'minus',
      'x',
      'check',
      'check-check',
      'copy',
      'clipboard',
      'clipboard-copy',
      'clipboard-check',
      'clipboard-list',
      'clipboard-paste',
      'scissors',
      'trash',
      'trash-2',
      'pencil',
      'pen',
      'pen-tool',
      'eraser',
      'edit',
      'edit-2',
      'edit-3',
      'save',
      'save-all',
      'pin',
      'pin-off',
      'move',
      'hand',
      'grab',
      'pointer',
      'mouse-pointer',
      'mouse-pointer-2',
      'mouse-pointer-click',
      'scan',
      'scan-line',
      'qr-code',
      'share',
      'share-2',
      'send',
      'send-horizontal',
      'reply',
      'reply-all',
      'forward',
      'link',
      'link-2',
      'unlink',
      'unlink-2',
      'merge',
      'split',
      'filter',
      'filter-x',
      'sort-asc',
      'sort-desc',
    ],
  },
  {
    name: 'media',
    label: '媒体',
    prefix: 'lucide',
    icons: [
      'image',
      'image-plus',
      'image-minus',
      'image-off',
      'images',
      'camera',
      'camera-off',
      'video',
      'video-off',
      'film',
      'play',
      'pause',
      'play-circle',
      'pause-circle',
      'stop-circle',
      'skip-back',
      'skip-forward',
      'rewind',
      'fast-forward',
      'volume',
      'volume-1',
      'volume-2',
      'volume-x',
      'mic',
      'mic-off',
      'mic-2',
      'headphones',
      'music',
      'music-2',
      'music-3',
      'music-4',
      'radio',
      'podcast',
      'monitor',
      'monitor-off',
      'tv',
      'tv-2',
      'screen-share',
      'screen-share-off',
      'cast',
      'airplay',
    ],
  },
  {
    name: 'files',
    label: '文件',
    prefix: 'lucide',
    icons: [
      'file',
      'file-plus',
      'file-minus',
      'file-x',
      'file-check',
      'file-text',
      'file-code',
      'file-code-2',
      'file-json',
      'file-json-2',
      'file-image',
      'file-video',
      'file-audio',
      'file-archive',
      'file-spreadsheet',
      'file-type',
      'file-type-2',
      'file-search',
      'file-search-2',
      'file-input',
      'file-output',
      'file-edit',
      'file-lock',
      'file-lock-2',
      'file-warning',
      'file-question',
      'files',
      'folder',
      'folder-plus',
      'folder-minus',
      'folder-x',
      'folder-check',
      'folder-open',
      'folder-closed',
      'folder-archive',
      'folder-search',
      'folder-input',
      'folder-output',
      'folder-tree',
      'folders',
      'archive',
      'archive-restore',
      'package',
      'package-2',
      'package-check',
      'package-minus',
      'package-plus',
      'package-x',
    ],
  },
  {
    name: 'ui',
    label: '界面',
    prefix: 'lucide',
    icons: [
      'menu',
      'more-horizontal',
      'more-vertical',
      'ellipsis',
      'list',
      'list-checks',
      'list-filter',
      'list-minus',
      'list-ordered',
      'list-plus',
      'list-restart',
      'list-todo',
      'list-tree',
      'list-video',
      'list-x',
      'table',
      'table-2',
      'kanban',
      'kanban-square',
      'calendar',
      'calendar-check',
      'calendar-check-2',
      'calendar-clock',
      'calendar-days',
      'calendar-heart',
      'calendar-minus',
      'calendar-off',
      'calendar-plus',
      'calendar-range',
      'calendar-search',
      'calendar-x',
      'calendar-x-2',
      'clock',
      'clock-1',
      'clock-2',
      'clock-3',
      'clock-4',
      'clock-5',
      'clock-6',
      'clock-7',
      'clock-8',
      'clock-9',
      'clock-10',
      'clock-11',
      'clock-12',
      'timer',
      'timer-off',
      'timer-reset',
      'alarm-clock',
      'alarm-clock-off',
      'hourglass',
      'history',
    ],
  },
  {
    name: 'communication',
    label: '通讯',
    prefix: 'lucide',
    icons: [
      'mail',
      'mail-check',
      'mail-minus',
      'mail-open',
      'mail-plus',
      'mail-question',
      'mail-search',
      'mail-warning',
      'mail-x',
      'mails',
      'inbox',
      'send',
      'send-horizontal',
      'message-circle',
      'message-circle-more',
      'message-square',
      'message-square-dashed',
      'message-square-plus',
      'message-square-text',
      'messages-square',
      'at-sign',
      'hash',
      'bell',
      'bell-dot',
      'bell-minus',
      'bell-off',
      'bell-plus',
      'bell-ring',
      'megaphone',
      'phone',
      'phone-call',
      'phone-forwarded',
      'phone-incoming',
      'phone-missed',
      'phone-off',
      'phone-outgoing',
      'voicemail',
      'contact',
      'contact-2',
      'contacts',
      'video',
      'video-off',
    ],
  },
  {
    name: 'user',
    label: '用户',
    prefix: 'lucide',
    icons: [
      'user',
      'user-2',
      'user-check',
      'user-check-2',
      'user-cog',
      'user-cog-2',
      'user-minus',
      'user-minus-2',
      'user-plus',
      'user-plus-2',
      'user-x',
      'user-x-2',
      'user-search',
      'user-round',
      'user-round-check',
      'user-round-cog',
      'user-round-minus',
      'user-round-plus',
      'user-round-search',
      'user-round-x',
      'user-round-pen',
      'users',
      'users-2',
      'users-round',
      'circle-user',
      'circle-user-round',
      'badge',
      'badge-check',
      'badge-minus',
      'badge-plus',
      'badge-x',
      'id-card',
      'fingerprint',
      'scan-face',
      'smile',
      'smile-plus',
      'frown',
      'meh',
      'angry',
      'annoyed',
      'laugh',
    ],
  },
  {
    name: 'security',
    label: '安全',
    prefix: 'lucide',
    icons: [
      'lock',
      'lock-keyhole',
      'lock-keyhole-open',
      'lock-open',
      'unlock',
      'unlock-keyhole',
      'key',
      'key-round',
      'key-square',
      'shield',
      'shield-alert',
      'shield-ban',
      'shield-check',
      'shield-minus',
      'shield-off',
      'shield-plus',
      'shield-question',
      'shield-x',
      'shield-half',
      'eye',
      'eye-off',
      'scan',
      'scan-face',
      'scan-line',
      'fingerprint',
      'bug',
      'bug-off',
      'bug-play',
      'skull',
      'siren',
      'alert-circle',
      'alert-octagon',
      'alert-triangle',
      'ban',
      'circle-slash',
      'circle-slash-2',
      'octagon',
      'octagon-alert',
      'octagon-x',
    ],
  },
  {
    name: 'status',
    label: '状态',
    prefix: 'lucide',
    icons: [
      'check',
      'check-check',
      'check-circle',
      'check-circle-2',
      'x',
      'x-circle',
      'x-octagon',
      'x-square',
      'circle',
      'circle-dot',
      'circle-dashed',
      'circle-alert',
      'circle-check',
      'circle-check-big',
      'circle-help',
      'circle-minus',
      'circle-off',
      'circle-pause',
      'circle-play',
      'circle-plus',
      'circle-stop',
      'circle-x',
      'square',
      'square-check',
      'square-check-big',
      'square-minus',
      'square-plus',
      'square-x',
      'info',
      'help-circle',
      'alert-circle',
      'alert-triangle',
      'alert-octagon',
      'loader',
      'loader-2',
      'loader-circle',
      'refresh-cw',
      'refresh-ccw',
      'rotate-cw',
      'rotate-ccw',
    ],
  },
  {
    name: 'commerce',
    label: '商业',
    prefix: 'lucide',
    icons: [
      'shopping-cart',
      'shopping-bag',
      'shopping-basket',
      'store',
      'store-front',
      'credit-card',
      'wallet',
      'wallet-2',
      'wallet-cards',
      'banknote',
      'coins',
      'piggy-bank',
      'receipt',
      'receipt-text',
      'tag',
      'tags',
      'ticket',
      'barcode',
      'qr-code',
      'gift',
      'percent',
      'badge-percent',
      'badge-dollar-sign',
      'badge-euro',
      'dollar-sign',
      'euro',
      'pound-sterling',
      'japanese-yen',
      'indian-rupee',
      'russian-ruble',
      'swiss-franc',
      'bitcoin',
      'circle-dollar-sign',
      'hand-coins',
      'trending-up',
      'trending-down',
      'bar-chart',
      'bar-chart-2',
      'bar-chart-3',
      'bar-chart-4',
      'bar-chart-big',
      'bar-chart-horizontal',
      'bar-chart-horizontal-big',
      'line-chart',
      'pie-chart',
      'activity',
    ],
  },
  {
    name: 'development',
    label: '开发',
    prefix: 'lucide',
    icons: [
      'code',
      'code-2',
      'code-xml',
      'terminal',
      'terminal-square',
      'square-terminal',
      'braces',
      'brackets',
      'parentheses',
      'regex',
      'variable',
      'bug',
      'bug-off',
      'bug-play',
      'git-branch',
      'git-branch-plus',
      'git-commit',
      'git-commit-horizontal',
      'git-commit-vertical',
      'git-compare',
      'git-compare-arrows',
      'git-fork',
      'git-graph',
      'git-merge',
      'git-pull-request',
      'git-pull-request-arrow',
      'git-pull-request-closed',
      'git-pull-request-create',
      'git-pull-request-create-arrow',
      'git-pull-request-draft',
      'github',
      'gitlab',
      'database',
      'database-backup',
      'database-zap',
      'server',
      'server-cog',
      'server-crash',
      'server-off',
      'cpu',
      'hard-drive',
      'hard-drive-download',
      'hard-drive-upload',
      'memory-stick',
      'binary',
      'cloud',
      'cloud-cog',
      'cloud-download',
      'cloud-off',
      'cloud-upload',
    ],
  },
  {
    name: 'navigation',
    label: '导航',
    prefix: 'lucide',
    icons: [
      'home',
      'house',
      'building',
      'building-2',
      'factory',
      'warehouse',
      'map',
      'map-pin',
      'map-pinned',
      'map-pin-off',
      'navigation',
      'navigation-2',
      'navigation-off',
      'compass',
      'locate',
      'locate-fixed',
      'locate-off',
      'crosshair',
      'target',
      'milestone',
      'signpost',
      'signpost-big',
      'route',
      'flag',
      'flag-off',
      'flag-triangle-left',
      'flag-triangle-right',
      'globe',
      'globe-2',
      'earth',
      'land-plot',
      'mountain',
      'mountain-snow',
      'tent',
      'trees',
      'tree-pine',
      'tree-deciduous',
    ],
  },
  {
    name: 'shapes',
    label: '形状',
    prefix: 'lucide',
    icons: [
      'circle',
      'square',
      'triangle',
      'pentagon',
      'hexagon',
      'octagon',
      'diamond',
      'heart',
      'star',
      'sparkle',
      'sparkles',
      'zap',
      'zap-off',
      'bolt',
      'flame',
      'flame-kindling',
      'sun',
      'moon',
      'moon-star',
      'sun-moon',
      'sun-dim',
      'sun-medium',
      'sun-snow',
      'sunrise',
      'sunset',
      'cloud',
      'cloud-sun',
      'cloud-moon',
      'cloud-rain',
      'cloud-drizzle',
      'cloud-snow',
      'cloud-fog',
      'cloud-lightning',
      'cloud-hail',
      'rainbow',
      'snowflake',
      'wind',
      'droplet',
      'droplets',
      'waves',
      'thermometer',
      'thermometer-sun',
      'thermometer-snowflake',
      'umbrella',
      'umbrella-off',
    ],
  },
  {
    name: 'tools',
    label: '工具',
    prefix: 'lucide',
    icons: [
      'settings',
      'settings-2',
      'sliders-horizontal',
      'sliders-vertical',
      'wrench',
      'hammer',
      'screwdriver',
      'nut',
      'cog',
      'tool',
      'ruler',
      'palette',
      'paint-bucket',
      'paintbrush',
      'paintbrush-2',
      'brush',
      'roller',
      'pipette',
      'pipette-off',
      'paint-roller',
      'highlighter',
      'wand',
      'wand-2',
      'magic-wand',
      'gauge',
      'gauge-circle',
      'thermometer',
      'scale',
      'scale-3d',
      'magnet',
      'lightbulb',
      'lightbulb-off',
      'flashlight',
      'flashlight-off',
      'lamp',
      'lamp-ceiling',
      'lamp-desk',
      'lamp-floor',
      'lamp-wall-down',
      'lamp-wall-up',
      'plug',
      'plug-2',
      'plug-zap',
      'plug-zap-2',
      'power',
      'power-off',
      'battery',
      'battery-charging',
      'battery-full',
      'battery-low',
      'battery-medium',
      'battery-warning',
    ],
  },
  {
    name: 'text',
    label: '文字',
    prefix: 'lucide',
    icons: [
      'type',
      'text',
      'text-cursor',
      'text-cursor-input',
      'text-select',
      'text-quote',
      'quote',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'subscript',
      'superscript',
      'align-left',
      'align-center',
      'align-right',
      'align-justify',
      'indent',
      'outdent',
      'pilcrow',
      'pilcrow-square',
      'heading',
      'heading-1',
      'heading-2',
      'heading-3',
      'heading-4',
      'heading-5',
      'heading-6',
      'list',
      'list-ordered',
      'list-tree',
      'list-checks',
      'list-minus',
      'list-plus',
      'list-x',
      'spell-check',
      'spell-check-2',
      'whole-word',
      'case-lower',
      'case-upper',
      'case-sensitive',
      'a-arrow-down',
      'a-arrow-up',
      'a-large-small',
      'font-picker',
      'book',
      'book-open',
      'book-open-check',
      'book-open-text',
      'book-text',
      'library',
      'library-big',
      'notebook',
      'notebook-pen',
      'notebook-text',
    ],
  },
  {
    name: 'misc',
    label: '其他',
    prefix: 'lucide',
    icons: [
      'search',
      'search-check',
      'search-code',
      'search-slash',
      'search-x',
      'zoom-in',
      'zoom-out',
      'printer',
      'printer-check',
      'calculator',
      'calculator-off',
      'keyboard',
      'mouse',
      'mouse-2',
      'mouse-off',
      'mouse-pointer',
      'mouse-pointer-2',
      'mouse-pointer-click',
      'touchpad',
      'touchpad-off',
      'smartphone',
      'tablet',
      'tablet-smartphone',
      'laptop',
      'laptop-2',
      'desktop',
      'monitor',
      'monitor-check',
      'monitor-dot',
      'monitor-off',
      'monitor-pause',
      'monitor-play',
      'monitor-smartphone',
      'monitor-speaker',
      'monitor-stop',
      'monitor-up',
      'monitor-x',
      'watch',
      'gamepad',
      'gamepad-2',
      'joystick',
      'dice-1',
      'dice-2',
      'dice-3',
      'dice-4',
      'dice-5',
      'dice-6',
      'puzzle',
      'toy-brick',
      'blocks',
    ],
  },
];

/**
 * 项目自定义 SVG 图标分类
 */
export const SVG_CATEGORY: IconCategory = {
  name: 'svg',
  label: '项目图标',
  prefix: 'svg',
  icons: PROJECT_SVG_ICONS,
};

/**
 * 所有分类（包含项目 SVG 和 Lucide）
 */
export const ALL_CATEGORIES: IconCategory[] = [
  SVG_CATEGORY,
  ...LUCIDE_CATEGORIES,
];

/**
 * Lucide 图标扁平列表
 */
export const ALL_LUCIDE_ICONS: string[] = LUCIDE_CATEGORIES.flatMap(
  (cat) => cat.icons,
);

/**
 * 所有图标扁平列表（包含前缀）
 */
export const ALL_ICONS_WITH_PREFIX: string[] = [
  ...PROJECT_SVG_ICONS.map((icon) => `svg:${icon}`),
  ...ALL_LUCIDE_ICONS.map((icon) => `lucide:${icon}`),
];

/**
 * 获取图标的完整名称（带前缀）
 */
export function getFullIconName(iconName: string, prefix: string): string {
  return `${prefix}:${iconName}`;
}
