"""add tenant plan tables

Revision ID: f785c12f1c4f
Revises: migrate_tenant_settings
Create Date: 2026-01-17 16:53:50.971612+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f785c12f1c4f'
down_revision: Union[str, None] = 'migrate_tenant_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_plans',
    sa.Column('code', sa.String(length=50), nullable=False, comment='套餐代码（如 free/pro/enterprise）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='套餐名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='套餐描述'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='价格'),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False, comment='计费周期: monthly/yearly/lifetime/custom'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序顺序'),
    sa.Column('quota', sa.JSON(), nullable=True, comment='配额配置'),
    sa.Column('features', sa.JSON(), nullable=True, comment='特性标记'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_plans_billing_cycle'), 'tenant_plans', ['billing_cycle'], unique=False)
    op.create_index(op.f('ix_tenant_plans_code'), 'tenant_plans', ['code'], unique=True)
    op.create_index(op.f('ix_tenant_plans_id'), 'tenant_plans', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_plans_is_active'), 'tenant_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenant_plans_is_deleted'), 'tenant_plans', ['is_deleted'], unique=False)
    op.create_table('tenant_plan_permissions',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['tenant_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'permission_id')
    )
    op.add_column('tenants', sa.Column('plan_id', sa.Integer(), nullable=True, comment='关联套餐ID'))
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='套餐类型(已废弃)',
               existing_comment='套餐类型')
    op.alter_column('tenants', 'quota',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='配额配置(可覆盖套餐默认值)',
               existing_comment='配额配置',
               existing_nullable=True)
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='租户设置(已废弃)',
               existing_comment='租户设置',
               existing_nullable=True)
    op.create_index(op.f('ix_tenants_plan_id'), 'tenants', ['plan_id'], unique=False)
    op.create_foreign_key('fk_tenants_plan_id', 'tenants', 'tenant_plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_plan_id', 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_plan_id'), table_name='tenants')
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='租户设置',
               existing_comment='租户设置(已废弃)',
               existing_nullable=True)
    op.alter_column('tenants', 'quota',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='配额配置',
               existing_comment='配额配置(可覆盖套餐默认值)',
               existing_nullable=True)
    op.alter_column('tenants', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='套餐类型',
               existing_comment='套餐类型(已废弃)')
    op.drop_column('tenants', 'plan_id')
    op.drop_table('tenant_plan_permissions')
    op.drop_index(op.f('ix_tenant_plans_is_deleted'), table_name='tenant_plans')
    op.drop_index(op.f('ix_tenant_plans_is_active'), table_name='tenant_plans')
    op.drop_index(op.f('ix_tenant_plans_id'), table_name='tenant_plans')
    op.drop_index(op.f('ix_tenant_plans_code'), table_name='tenant_plans')
    op.drop_index(op.f('ix_tenant_plans_billing_cycle'), table_name='tenant_plans')
    op.drop_table('tenant_plans')
    # ### end Alembic commands ###
