# -*- coding: utf-8 -*-
"""add_organization_fields_to_roles

Revision ID: bd94c7f44d6c
Revises: 13da4a77114f
Create Date: 2026-01-15 17:34:18.186672+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd94c7f44d6c'
down_revision: Union[str, None] = '13da4a77114f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # admin_roles 表
    op.add_column('admin_roles', sa.Column('type', sa.String(length=20), server_default='role', nullable=False, comment='节点类型: department/position/role'))
    op.add_column('admin_roles', sa.Column('allow_members', sa.Boolean(), server_default='true', nullable=False, comment='是否允许添加成员'))
    op.add_column('admin_roles', sa.Column('leader_id', sa.Integer(), nullable=True, comment='负责人 ID'))
    op.create_index('ix_admin_roles_type', 'admin_roles', ['type'], unique=False)
    op.create_index('ix_admin_roles_leader_id', 'admin_roles', ['leader_id'], unique=False)
    op.create_foreign_key('fk_admin_roles_leader_id', 'admin_roles', 'admins', ['leader_id'], ['id'], ondelete='SET NULL')
    
    # tenant_admin_roles 表
    op.add_column('tenant_admin_roles', sa.Column('type', sa.String(length=20), server_default='role', nullable=False, comment='节点类型: department/position/role'))
    op.add_column('tenant_admin_roles', sa.Column('allow_members', sa.Boolean(), server_default='true', nullable=False, comment='是否允许添加成员'))
    op.add_column('tenant_admin_roles', sa.Column('leader_id', sa.Integer(), nullable=True, comment='负责人 ID'))
    op.create_index('ix_tenant_admin_roles_type', 'tenant_admin_roles', ['type'], unique=False)
    op.create_index('ix_tenant_admin_roles_leader_id', 'tenant_admin_roles', ['leader_id'], unique=False)
    op.create_foreign_key('fk_tenant_admin_roles_leader_id', 'tenant_admin_roles', 'tenant_admins', ['leader_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # tenant_admin_roles 表
    op.drop_constraint('fk_tenant_admin_roles_leader_id', 'tenant_admin_roles', type_='foreignkey')
    op.drop_index('ix_tenant_admin_roles_type', table_name='tenant_admin_roles')
    op.drop_index('ix_tenant_admin_roles_leader_id', table_name='tenant_admin_roles')
    op.drop_column('tenant_admin_roles', 'leader_id')
    op.drop_column('tenant_admin_roles', 'allow_members')
    op.drop_column('tenant_admin_roles', 'type')
    
    # admin_roles 表
    op.drop_constraint('fk_admin_roles_leader_id', 'admin_roles', type_='foreignkey')
    op.drop_index('ix_admin_roles_type', table_name='admin_roles')
    op.drop_index('ix_admin_roles_leader_id', table_name='admin_roles')
    op.drop_column('admin_roles', 'leader_id')
    op.drop_column('admin_roles', 'allow_members')
    op.drop_column('admin_roles', 'type')
    # ### end Alembic commands ###
