"""add_operation_log_table

Revision ID: c63b0c9f4a25
Revises: f785c12f1c4f
Create Date: 2026-01-20 15:35:55.142586+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63b0c9f4a25'
down_revision: Union[str, None] = 'f785c12f1c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_logs',
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='租户ID（平台操作为空）'),
    sa.Column('user_type', sa.String(length=20), nullable=False, comment='用户类型'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('module', sa.String(length=50), nullable=True, comment='业务模块'),
    sa.Column('action', sa.String(length=20), nullable=True, comment='操作类型'),
    sa.Column('resource', sa.String(length=100), nullable=True, comment='资源标识（权限代码）'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP 方法'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='请求路径'),
    sa.Column('query_params', sa.JSON(), nullable=True, comment='查询参数'),
    sa.Column('request_body', sa.JSON(), nullable=True, comment='请求体摘要（已脱敏）'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP 响应状态码'),
    sa.Column('response_code', sa.Integer(), nullable=True, comment='业务响应码'),
    sa.Column('response_message', sa.String(length=500), nullable=True, comment='响应消息'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='客户端 IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='请求耗时（毫秒）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_operation_logs_ip'), 'operation_logs', ['ip'], unique=False)
    op.create_index(op.f('ix_operation_logs_is_deleted'), 'operation_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_operation_logs_module'), 'operation_logs', ['module'], unique=False)
    op.create_index('ix_operation_logs_module_action', 'operation_logs', ['module', 'action'], unique=False)
    op.create_index(op.f('ix_operation_logs_path'), 'operation_logs', ['path'], unique=False)
    op.create_index(op.f('ix_operation_logs_resource'), 'operation_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_operation_logs_response_code'), 'operation_logs', ['response_code'], unique=False)
    op.create_index('ix_operation_logs_tenant_created', 'operation_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_tenant_id'), 'operation_logs', ['tenant_id'], unique=False)
    op.create_index('ix_operation_logs_user', 'operation_logs', ['user_type', 'user_id'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_type'), 'operation_logs', ['user_type'], unique=False)
    op.create_index(op.f('ix_operation_logs_username'), 'operation_logs', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_logs_username'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_user_type'), table_name='operation_logs')
    op.drop_index('ix_operation_logs_user', table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_tenant_id'), table_name='operation_logs')
    op.drop_index('ix_operation_logs_tenant_created', table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_response_code'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_resource'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_path'), table_name='operation_logs')
    op.drop_index('ix_operation_logs_module_action', table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_module'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_is_deleted'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_ip'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_table('operation_logs')
    # ### end Alembic commands ###
