"""add plugin scope and tenant assignments

Revision ID: 5c37f4f986ac
Revises: 20260222_rm_oai
Create Date: 2026-02-21 19:57:43.561827+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c37f4f986ac'
down_revision: Union[str, None] = '20260222_rm_oai'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_tenant_assignments',
    sa.Column('plugin_id', sa.Integer(), nullable=False, comment='插件 ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='企业 ID'),
    sa.Column('assigned_by', sa.Integer(), nullable=True, comment='分配操作的管理员 ID'),
    sa.Column('assigned_at', sa.DateTime(), nullable=False, comment='分配时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.String(length=20), nullable=True, comment='删除层级: tenant=企业回收站, admin=管理端回收站'),
    sa.ForeignKeyConstraint(['assigned_by'], ['admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'tenant_id', name='uq_plugin_tenant_assignments_plugin_tenant')
    )
    op.create_index(op.f('ix_plugin_tenant_assignments_id'), 'plugin_tenant_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_tenant_assignments_is_deleted'), 'plugin_tenant_assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plugin_tenant_assignments_plugin_id'), 'plugin_tenant_assignments', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_plugin_tenant_assignments_tenant_id'), 'plugin_tenant_assignments', ['tenant_id'], unique=False)
    op.add_column('plugins', sa.Column('scope', sa.String(), nullable=False, server_default='all_tenants', comment='作用域（platform_only/all_tenants/assigned_tenants/global）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugins', 'scope')
    op.drop_index(op.f('ix_plugin_tenant_assignments_tenant_id'), table_name='plugin_tenant_assignments')
    op.drop_index(op.f('ix_plugin_tenant_assignments_plugin_id'), table_name='plugin_tenant_assignments')
    op.drop_index(op.f('ix_plugin_tenant_assignments_is_deleted'), table_name='plugin_tenant_assignments')
    op.drop_index(op.f('ix_plugin_tenant_assignments_id'), table_name='plugin_tenant_assignments')
    op.drop_table('plugin_tenant_assignments')
    # ### end Alembic commands ###
