"""add plugin tables

Revision ID: d11f0b4fec39
Revises: c084bc659728
Create Date: 2026-02-23 02:43:36.879039+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd11f0b4fec39'
down_revision: Union[str, None] = 'c084bc659728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_licenses',
    sa.Column('plugin_id', sa.Integer(), nullable=False, comment='插件ID'),
    sa.Column('license_key', sa.String(length=500), nullable=True, comment='License Key'),
    sa.Column('license_type', sa.String(length=20), nullable=False, comment='许可类型'),
    sa.Column('version_scope', sa.String(length=50), nullable=True, comment='版本范围'),
    sa.Column('buyer_email', sa.String(length=200), nullable=True, comment='购买者邮箱'),
    sa.Column('issued_at', sa.DateTime(), nullable=True, comment='签发时间'),
    sa.Column('trial_expires_at', sa.DateTime(), nullable=True, comment='试用到期时间'),
    sa.Column('activated_at', sa.DateTime(), nullable=True, comment='激活时间'),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.String(length=20), nullable=True, comment='删除层级: tenant=租户回收站, admin=管理端回收站'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_licenses_id'), 'plugin_licenses', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_licenses_is_deleted'), 'plugin_licenses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plugin_licenses_plugin_id'), 'plugin_licenses', ['plugin_id'], unique=False)
    op.create_table('plugin_versions',
    sa.Column('plugin_id', sa.Integer(), nullable=False, comment='插件ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('manifest', sa.JSON(), nullable=False, comment='该版本清单'),
    sa.Column('changelog', sa.Text(), nullable=True, comment='变更日志'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='版本状态'),
    sa.Column('installed_at', sa.DateTime(), nullable=True, comment='安装时间'),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True, comment='回退时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.String(length=20), nullable=True, comment='删除层级: tenant=租户回收站, admin=管理端回收站'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_versions_id'), 'plugin_versions', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_versions_is_deleted'), 'plugin_versions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plugin_versions_plugin_id'), 'plugin_versions', ['plugin_id'], unique=False)
    op.drop_index(op.f('ix_tenant_plugins_id'), table_name='tenant_plugins')
    op.drop_index(op.f('ix_tenant_plugins_is_deleted'), table_name='tenant_plugins')
    op.drop_index(op.f('ix_tenant_plugins_plugin_id'), table_name='tenant_plugins')
    op.drop_index(op.f('ix_tenant_plugins_tenant_id'), table_name='tenant_plugins')
    op.drop_table('tenant_plugins')
    op.drop_index(op.f('ix_plugin_migrations_id'), table_name='plugin_migrations')
    op.drop_index(op.f('ix_plugin_migrations_is_deleted'), table_name='plugin_migrations')
    op.drop_index(op.f('ix_plugin_migrations_plugin_name'), table_name='plugin_migrations')
    op.drop_table('plugin_migrations')
    op.add_column('plugin_tenant_assignments', sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'))
    op.add_column('plugin_tenant_assignments', sa.Column('config', sa.JSON(), nullable=False, comment='租户级配置'))
    op.alter_column('plugin_tenant_assignments', 'plugin_id',
               existing_type=sa.INTEGER(),
               comment='插件ID',
               existing_comment='插件 ID',
               existing_nullable=False)
    op.alter_column('plugin_tenant_assignments', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_comment='租户 ID',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_plugin_tenant_assignments_plugin_tenant'), 'plugin_tenant_assignments', type_='unique')
    op.create_unique_constraint('uq_plugin_tenant', 'plugin_tenant_assignments', ['plugin_id', 'tenant_id'])
    op.drop_constraint(op.f('plugin_tenant_assignments_assigned_by_fkey'), 'plugin_tenant_assignments', type_='foreignkey')
    op.drop_column('plugin_tenant_assignments', 'assigned_at')
    op.drop_column('plugin_tenant_assignments', 'assigned_by')
    op.add_column('plugins', sa.Column('icon_color', sa.String(length=20), nullable=True, comment='图标颜色'))
    op.add_column('plugins', sa.Column('repository_url', sa.String(length=500), nullable=True, comment='仓库URL'))
    op.add_column('plugins', sa.Column('license_text', sa.String(length=50), nullable=True, comment='许可证'))
    op.add_column('plugins', sa.Column('tier', sa.String(length=20), nullable=False, comment='信任等级'))
    op.add_column('plugins', sa.Column('config', sa.JSON(), nullable=False, comment='全局配置'))
    op.add_column('plugins', sa.Column('ai_requirements', sa.JSON(), nullable=True, comment='AI需求'))
    op.add_column('plugins', sa.Column('pricing_type', sa.String(length=20), nullable=False, comment='定价类型'))
    op.add_column('plugins', sa.Column('pricing_info', sa.JSON(), nullable=True, comment='定价详情'))
    op.add_column('plugins', sa.Column('error_message', sa.Text(), nullable=True, comment='最近错误'))
    op.add_column('plugins', sa.Column('error_count', sa.Integer(), nullable=False, comment='连续错误次数'))
    op.add_column('plugins', sa.Column('installed_packages', sa.JSON(), nullable=False, comment='已安装的Python依赖'))
    op.add_column('plugins', sa.Column('granted_capabilities', sa.JSON(), nullable=False, comment='管理员授权的能力列表'))
    op.add_column('plugins', sa.Column('installed_at', sa.DateTime(), nullable=True, comment='安装时间'))
    op.add_column('plugins', sa.Column('enabled_at', sa.DateTime(), nullable=True, comment='启用时间'))
    op.alter_column('plugins', 'name',
               existing_type=sa.VARCHAR(),
               comment='插件唯一标识',
               existing_comment='插件唯一标识（如 novusai-anthropic-adapter）',
               existing_nullable=False)
    op.alter_column('plugins', 'display_name',
               existing_type=sa.VARCHAR(),
               comment='显示名称',
               existing_comment='插件显示名称',
               existing_nullable=False)
    op.alter_column('plugins', 'version',
               existing_type=sa.VARCHAR(),
               comment='当前版本',
               existing_comment='当前版本号（semver）',
               existing_nullable=False)
    op.alter_column('plugins', 'description',
               existing_type=sa.TEXT(),
               comment='描述',
               existing_comment='插件描述',
               existing_nullable=True)
    op.alter_column('plugins', 'icon',
               existing_type=sa.VARCHAR(),
               comment='图标(Iconify字符串或图片URL)',
               existing_comment='插件图标（URL 或 Lucide 图标名）',
               existing_nullable=True)
    op.alter_column('plugins', 'homepage',
               existing_type=sa.VARCHAR(),
               comment='主页URL',
               existing_comment='插件主页 URL',
               existing_nullable=True)
    op.alter_column('plugins', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='标签',
               existing_comment='分类标签（如 ["ai", "adapter", "openai"]）',
               existing_nullable=True)
    op.alter_column('plugins', 'scope',
               existing_type=sa.VARCHAR(),
               comment='作用域',
               existing_comment='作用域（platform_only/all_tenants/assigned_tenants/global）',
               existing_nullable=False)
    op.alter_column('plugins', 'status',
               existing_type=sa.VARCHAR(),
               comment='状态',
               existing_comment='插件状态（installed/enabled/disabled/error）',
               existing_nullable=False)
    op.alter_column('plugins', 'install_source',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='安装来源',
               existing_comment='安装来源（local/marketplace/builtin/entry_point）')
    op.alter_column('plugins', 'marketplace_slug',
               existing_type=sa.VARCHAR(),
               comment='市场标识',
               existing_comment='插件市场 slug（市场安装时填写，用于后续升级匹配）',
               existing_nullable=True)
    op.alter_column('plugins', 'manifest',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               comment='清单内容',
               existing_comment='完整 manifest.json 内容')
    op.drop_index(op.f('ix_plugins_type_status'), table_name='plugins')
    op.drop_constraint(op.f('uq_plugins_name'), 'plugins', type_='unique')
    op.create_index('ix_plugins_name', 'plugins', ['name'], unique=True, postgresql_where='is_deleted = false')
    op.create_index('ix_plugins_scope', 'plugins', ['scope'], unique=False)
    op.create_index('ix_plugins_status', 'plugins', ['status'], unique=False)
    op.drop_column('plugins', 'default_config')
    op.drop_column('plugins', 'rating')
    op.drop_column('plugins', 'required_permissions')
    op.drop_column('plugins', 'is_system')
    op.drop_column('plugins', 'conflicts')
    op.drop_column('plugins', 'dependencies')
    op.drop_column('plugins', 'readme')
    op.drop_column('plugins', 'entry_point')
    op.drop_column('plugins', 'plugin_type')
    op.drop_column('plugins', 'version_history')
    op.drop_column('plugins', 'source_url')
    op.drop_column('plugins', 'screenshots')
    op.drop_column('plugins', 'license')
    op.drop_column('plugins', 'platform_version')
    op.drop_column('plugins', 'category')
    op.drop_column('plugins', 'config_schema')
    op.drop_column('plugins', 'downloads_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugins', sa.Column('downloads_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='下载/安装次数（插件市场统计）'))
    op.add_column('plugins', sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='配置项 JSON Schema（用于前端动态表单渲染）'))
    op.add_column('plugins', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True, comment='插件分类（如 ai-model, productivity, analytics）'))
    op.add_column('plugins', sa.Column('platform_version', sa.VARCHAR(), autoincrement=False, nullable=True, comment='最低平台版本要求（如 >=2.0.0）'))
    op.add_column('plugins', sa.Column('license', sa.VARCHAR(), autoincrement=False, nullable=True, comment='开源许可证（如 MIT, Apache-2.0）'))
    op.add_column('plugins', sa.Column('screenshots', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='截图 URL 列表（插件市场展示）'))
    op.add_column('plugins', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True, comment='插件源码仓库 URL（如 GitHub 地址）'))
    op.add_column('plugins', sa.Column('version_history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='版本历史记录'))
    op.add_column('plugins', sa.Column('plugin_type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='插件类型（adapter/tool/hook/api/skill/composite）'))
    op.add_column('plugins', sa.Column('entry_point', sa.VARCHAR(), autoincrement=False, nullable=False, comment='入口点（如 app.plugins.anthropic.main.AnthropicPlugin）'))
    op.add_column('plugins', sa.Column('readme', sa.TEXT(), autoincrement=False, nullable=True, comment='README 内容（Markdown）'))
    op.add_column('plugins', sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='依赖声明（如 {"novusai-core": ">=1.0.0"}）'))
    op.add_column('plugins', sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='互斥插件列表（如 ["old-adapter"]）'))
    op.add_column('plugins', sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否为系统内置插件（不可卸载/禁用）'))
    op.add_column('plugins', sa.Column('required_permissions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='所需权限声明列表（如 ["db:read", "http:outbound"]）'))
    op.add_column('plugins', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='评分（1.0-5.0，插件市场）'))
    op.add_column('plugins', sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='默认配置值'))
    op.drop_index('ix_plugins_status', table_name='plugins')
    op.drop_index('ix_plugins_scope', table_name='plugins')
    op.drop_index('ix_plugins_name', table_name='plugins', postgresql_where='is_deleted = false')
    op.create_unique_constraint(op.f('uq_plugins_name'), 'plugins', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_plugins_type_status'), 'plugins', ['plugin_type', 'status'], unique=False)
    op.alter_column('plugins', 'manifest',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               comment='完整 manifest.json 内容',
               existing_comment='清单内容')
    op.alter_column('plugins', 'marketplace_slug',
               existing_type=sa.VARCHAR(),
               comment='插件市场 slug（市场安装时填写，用于后续升级匹配）',
               existing_comment='市场标识',
               existing_nullable=True)
    op.alter_column('plugins', 'install_source',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='安装来源（local/marketplace/builtin/entry_point）',
               existing_comment='安装来源')
    op.alter_column('plugins', 'status',
               existing_type=sa.VARCHAR(),
               comment='插件状态（installed/enabled/disabled/error）',
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('plugins', 'scope',
               existing_type=sa.VARCHAR(),
               comment='作用域（platform_only/all_tenants/assigned_tenants/global）',
               existing_comment='作用域',
               existing_nullable=False)
    op.alter_column('plugins', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='分类标签（如 ["ai", "adapter", "openai"]）',
               existing_comment='标签',
               existing_nullable=True)
    op.alter_column('plugins', 'homepage',
               existing_type=sa.VARCHAR(),
               comment='插件主页 URL',
               existing_comment='主页URL',
               existing_nullable=True)
    op.alter_column('plugins', 'icon',
               existing_type=sa.VARCHAR(),
               comment='插件图标（URL 或 Lucide 图标名）',
               existing_comment='图标(Iconify字符串或图片URL)',
               existing_nullable=True)
    op.alter_column('plugins', 'description',
               existing_type=sa.TEXT(),
               comment='插件描述',
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('plugins', 'version',
               existing_type=sa.VARCHAR(),
               comment='当前版本号（semver）',
               existing_comment='当前版本',
               existing_nullable=False)
    op.alter_column('plugins', 'display_name',
               existing_type=sa.VARCHAR(),
               comment='插件显示名称',
               existing_comment='显示名称',
               existing_nullable=False)
    op.alter_column('plugins', 'name',
               existing_type=sa.VARCHAR(),
               comment='插件唯一标识（如 novusai-anthropic-adapter）',
               existing_comment='插件唯一标识',
               existing_nullable=False)
    op.drop_column('plugins', 'enabled_at')
    op.drop_column('plugins', 'installed_at')
    op.drop_column('plugins', 'granted_capabilities')
    op.drop_column('plugins', 'installed_packages')
    op.drop_column('plugins', 'error_count')
    op.drop_column('plugins', 'error_message')
    op.drop_column('plugins', 'pricing_info')
    op.drop_column('plugins', 'pricing_type')
    op.drop_column('plugins', 'ai_requirements')
    op.drop_column('plugins', 'config')
    op.drop_column('plugins', 'tier')
    op.drop_column('plugins', 'license_text')
    op.drop_column('plugins', 'repository_url')
    op.drop_column('plugins', 'icon_color')
    op.add_column('plugin_tenant_assignments', sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=True, comment='分配操作的管理员 ID'))
    op.add_column('plugin_tenant_assignments', sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='分配时间'))
    op.create_foreign_key(op.f('plugin_tenant_assignments_assigned_by_fkey'), 'plugin_tenant_assignments', 'admins', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_plugin_tenant', 'plugin_tenant_assignments', type_='unique')
    op.create_unique_constraint(op.f('uq_plugin_tenant_assignments_plugin_tenant'), 'plugin_tenant_assignments', ['plugin_id', 'tenant_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('plugin_tenant_assignments', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户 ID',
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('plugin_tenant_assignments', 'plugin_id',
               existing_type=sa.INTEGER(),
               comment='插件 ID',
               existing_comment='插件ID',
               existing_nullable=False)
    op.drop_column('plugin_tenant_assignments', 'config')
    op.drop_column('plugin_tenant_assignments', 'is_active')
    op.create_table('plugin_migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plugin_name', sa.VARCHAR(), autoincrement=False, nullable=False, comment='插件名称'),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False, comment='迁移版本号（如 001, 002）'),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False, comment='迁移文件名（如 001_create_tables.sql）'),
    sa.Column('checksum', sa.VARCHAR(), autoincrement=False, nullable=False, comment='迁移文件 SHA256 校验和'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='迁移描述（从文件名或注释中提取）'),
    sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='迁移执行时间'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='删除层级: tenant=租户回收站, admin=管理端回收站'),
    sa.PrimaryKeyConstraint('id', name=op.f('plugin_migrations_pkey')),
    sa.UniqueConstraint('plugin_name', 'version', name=op.f('uq_plugin_migrations_name_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_plugin_migrations_plugin_name'), 'plugin_migrations', ['plugin_name'], unique=False)
    op.create_index(op.f('ix_plugin_migrations_is_deleted'), 'plugin_migrations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plugin_migrations_id'), 'plugin_migrations', ['id'], unique=False)
    op.create_table('tenant_plugins',
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='租户 ID'),
    sa.Column('plugin_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='插件 ID'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否启用'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='租户自定义配置（覆盖插件默认配置）'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='删除层级: tenant=租户回收站, admin=管理端回收站'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], name=op.f('tenant_plugins_plugin_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_plugins_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_plugins_pkey')),
    sa.UniqueConstraint('tenant_id', 'plugin_id', name=op.f('uq_tenant_plugins_tenant_plugin'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tenant_plugins_tenant_id'), 'tenant_plugins', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_plugins_plugin_id'), 'tenant_plugins', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_tenant_plugins_is_deleted'), 'tenant_plugins', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenant_plugins_id'), 'tenant_plugins', ['id'], unique=False)
    op.drop_index(op.f('ix_plugin_versions_plugin_id'), table_name='plugin_versions')
    op.drop_index(op.f('ix_plugin_versions_is_deleted'), table_name='plugin_versions')
    op.drop_index(op.f('ix_plugin_versions_id'), table_name='plugin_versions')
    op.drop_table('plugin_versions')
    op.drop_index(op.f('ix_plugin_licenses_plugin_id'), table_name='plugin_licenses')
    op.drop_index(op.f('ix_plugin_licenses_is_deleted'), table_name='plugin_licenses')
    op.drop_index(op.f('ix_plugin_licenses_id'), table_name='plugin_licenses')
    op.drop_table('plugin_licenses')
    # ### end Alembic commands ###
