"""add_notification_tables

Revision ID: 6b4fe69b2efc
Revises: 0e818abf253a
Create Date: 2026-02-21 05:26:43.411813+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b4fe69b2efc'
down_revision: Union[str, None] = '0e818abf253a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('user_type', sa.String(length=20), nullable=False, comment='用户类型'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, server_default="0", comment='租户 ID（0 = 平台级）'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户 ID（NULL = 全局记录）'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='通知分类: system/ai/task/biz/audit'),
    sa.Column('channel_ws', sa.Boolean(), nullable=False, comment='是否接收 WS 实时推送'),
    sa.Column('channel_email', sa.Boolean(), nullable=False, comment='是否接收邮件通知'),
    sa.Column('channel_inbox', sa.Boolean(), nullable=False, comment='是否写入收件箱'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.String(length=20), nullable=True, comment='删除层级: tenant=企业回收站, admin=管理端回收站'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_type', 'tenant_id', 'user_id', 'category', name='uq_notification_pref_v2')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_is_deleted'), 'notification_preferences', ['is_deleted'], unique=False)
    op.create_table('notification_templates',
    sa.Column('code', sa.String(length=100), nullable=False, comment='模板编码'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类: system/ai/task/biz/audit'),
    sa.Column('title_template', sa.Text(), nullable=False, comment='标题模板'),
    sa.Column('body_template', sa.Text(), nullable=True, comment='正文模板（Markdown）'),
    sa.Column('channels', postgresql.ARRAY(sa.String(length=20)), nullable=True, comment='投递渠道'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: low/normal/high/urgent'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否系统内置'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='企业 ID（NULL=系统级）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.String(length=20), nullable=True, comment='删除层级: tenant=企业回收站, admin=管理端回收站'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_notification_templates_category'), 'notification_templates', ['category'], unique=False)
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_index(op.f('ix_notification_templates_is_deleted'), 'notification_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notification_templates_tenant_id'), 'notification_templates', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='企业 ID（NULL=平台级）'),
    sa.Column('recipient_type', sa.String(length=20), nullable=False, comment='接收人类型: admin/tenant_admin/tenant_user'),
    sa.Column('recipient_id', sa.Integer(), nullable=False, comment='接收人 ID'),
    sa.Column('template_code', sa.String(length=100), nullable=False, comment='通知模板编码'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类: system/ai/task/biz/audit'),
    sa.Column('title', sa.Text(), nullable=False, comment='通知标题（已渲染）'),
    sa.Column('body', sa.Text(), nullable=True, comment='通知正文（已渲染）'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='业务关联数据'),
    sa.Column('link', sa.String(length=500), nullable=True, comment='点击跳转链接'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级: low/normal/high/urgent'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='已读时间'),
    sa.Column('expired_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.String(length=20), nullable=True, comment='删除层级: tenant=企业回收站, admin=管理端回收站'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_recipient', 'notifications', ['recipient_type', 'recipient_id', 'is_read'], unique=False)
    op.create_index('idx_notifications_tenant', 'notifications', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_index('idx_notifications_tenant', table_name='notifications')
    op.drop_index('idx_notifications_recipient', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_templates_tenant_id'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_is_deleted'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_category'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_notification_preferences_is_deleted'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
