"""add plugin marketplace fields

Revision ID: 8c70188e6307
Revises: 20260213_plugins
Create Date: 2026-02-13 10:48:22.471162+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
try:
    import pgvector.sqlalchemy
except ImportError:
    pgvector = None

# revision identifiers, used by Alembic.
revision: str = '8c70188e6307'
down_revision: Union[str, None] = '20260213_plugins'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_versions', 'rag_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='agent.version.field.rag_config',
               existing_nullable=True)
    op.alter_column('agent_versions', 'context_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='agent.version.field.context_config',
               existing_nullable=True)
    op.alter_column('agent_versions', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='agent.version.field.output_schema',
               existing_nullable=True)
    op.alter_column('agents', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID（scope=tenant 时必填，global/admin_only 时为 NULL）',
               existing_comment='租户ID',
               existing_nullable=True)
    op.alter_column('agents', 'scope',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='enum.agent_model.scope',
               existing_nullable=False)
    op.alter_column('agents', 'knowledge_base_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_model.knowledge_base_ids',
               existing_comment='关联知识库 ID 列表',
               existing_nullable=True)
    op.alter_column('agents', 'rag_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_model.rag_config',
               existing_comment='RAG 配置',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'agent_id',
               existing_type=sa.INTEGER(),
               comment='ai_action_log.field.agent_id',
               existing_comment='智能体 ID',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment='ai_action_log.field.conversation_id',
               existing_comment='对话 ID',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'operator_id',
               existing_type=sa.INTEGER(),
               comment='ai_action_log.field.operator_id',
               existing_comment='操作者 ID',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'action_name',
               existing_type=sa.VARCHAR(length=100),
               comment='ai_action_log.field.action_name',
               existing_comment='操作名称',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'action_type',
               existing_type=sa.VARCHAR(length=50),
               comment='ai_action_log.field.action_type',
               existing_comment='操作类型',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'action_level',
               existing_type=sa.VARCHAR(length=50),
               comment='ai_action_log.field.action_level',
               existing_comment='安全等级',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'request_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='ai_action_log.field.request_data',
               existing_comment='请求数据',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'response_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='ai_action_log.field.response_data',
               existing_comment='响应数据',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='ai_action_log.field.status',
               existing_comment='执行状态',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment='ai_action_log.field.error_message',
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'duration_ms',
               existing_type=sa.INTEGER(),
               comment='ai_action_log.field.duration_ms',
               existing_comment='执行耗时（毫秒）',
               existing_nullable=True)
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.INTEGER(),
               comment='knowledge_base.chunk_model.document_id',
               existing_comment='文档 ID',
               existing_nullable=False)
    op.alter_column('document_chunks', 'knowledge_base_id',
               existing_type=sa.INTEGER(),
               comment='knowledge_base.chunk_model.knowledge_base_id',
               existing_comment='知识库 ID',
               existing_nullable=False)
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment='knowledge_base.chunk_model.chunk_index',
               existing_comment='块序号',
               existing_nullable=False)
    op.alter_column('document_chunks', 'content',
               existing_type=sa.TEXT(),
               comment='knowledge_base.chunk_model.content',
               existing_comment='分块文本内容',
               existing_nullable=False)
    op.alter_column('document_chunks', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='knowledge_base.chunk_model.content_hash',
               existing_comment='内容 MD5',
               existing_nullable=False)
    op.alter_column('document_chunks', 'char_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.chunk_model.char_count',
               existing_comment='字符数',
               existing_nullable=False)
    op.alter_column('document_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.chunk_model.token_count',
               existing_comment='Token 数',
               existing_nullable=False)
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment='knowledge_base.chunk_model.embedding',
               existing_nullable=True)
    op.alter_column('document_chunks', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='knowledge_base.chunk_model.metadata',
               existing_comment='元数据',
               existing_nullable=True)
    op.alter_column('document_chunks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.drop_index(op.f('ix_chunk_embedding'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_chunk_tsv'), table_name='document_chunks', postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_knowledge_base_id'), 'document_chunks', ['knowledge_base_id'], unique=False)
    op.drop_column('document_chunks', 'content_tsv')
    op.alter_column('knowledge_bases', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID（scope=tenant 时必填，global/admin_only 时为 NULL）',
               existing_comment='租户ID',
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'scope',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='knowledge_base.model.scope',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='knowledge_base.model.name',
               existing_comment='知识库名称',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'description',
               existing_type=sa.TEXT(),
               comment='knowledge_base.model.description',
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'avatar',
               existing_type=sa.VARCHAR(length=50),
               comment='knowledge_base.model.avatar',
               existing_comment='图标/颜色标识',
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'embedding_model_id',
               existing_type=sa.INTEGER(),
               comment='knowledge_base.model.embedding_model_id',
               existing_comment='Embedding 模型 ID',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'embedding_dimensions',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.model.embedding_dimensions',
               existing_comment='向量维度',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'chunk_size',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.model.chunk_size',
               existing_comment='分块大小',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'chunk_overlap',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.model.chunk_overlap',
               existing_comment='分块重叠',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'chunk_strategy',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='knowledge_base.model.chunk_strategy',
               existing_comment='分块策略',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'search_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='knowledge_base.model.search_mode',
               existing_comment='检索模式',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'top_k',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.model.top_k',
               existing_comment='默认返回数量',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'score_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='knowledge_base.model.score_threshold',
               existing_comment='最低相似度阈值',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'document_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.model.document_count',
               existing_comment='文档总数',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'total_chunks',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.model.total_chunks',
               existing_comment='分块总数',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'total_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.model.total_size_bytes',
               existing_comment='原始文件总大小',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='knowledge_base.model.status',
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'knowledge_base_id',
               existing_type=sa.INTEGER(),
               comment='knowledge_base.document_model.knowledge_base_id',
               existing_comment='知识库 ID',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'attachment_id',
               existing_type=sa.INTEGER(),
               comment='knowledge_base.document_model.attachment_id',
               existing_comment='附件 ID',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'file_name',
               existing_type=sa.VARCHAR(length=500),
               comment='knowledge_base.document_model.file_name',
               existing_comment='原始文件名',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='knowledge_base.document_model.file_type',
               existing_comment='文件类型',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'file_size',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.document_model.file_size',
               existing_comment='文件大小（字节）',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='knowledge_base.document_model.file_hash',
               existing_comment='MD5 哈希',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'source_url',
               existing_type=sa.TEXT(),
               comment='knowledge_base.document_model.source_url',
               existing_comment='网页来源 URL',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'metadata_extra',
               existing_type=sa.TEXT(),
               comment='knowledge_base.document_model.metadata_extra',
               existing_comment='扩展元数据',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='knowledge_base.document_model.status',
               existing_comment='处理状态',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'error_message',
               existing_type=sa.TEXT(),
               comment='knowledge_base.document_model.error_message',
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'error_stage',
               existing_type=sa.VARCHAR(length=20),
               comment='knowledge_base.document_model.error_stage',
               existing_comment='失败阶段',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.document_model.retry_count',
               existing_comment='重试次数',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.document_model.chunk_count',
               existing_comment='分块数量',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.document_model.token_count',
               existing_comment='文档总 Token 数',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'char_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='knowledge_base.document_model.char_count',
               existing_comment='文档总字符数',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'processing_started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='knowledge_base.document_model.processing_started_at',
               existing_comment='处理开始时间',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'processing_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='knowledge_base.document_model.processing_completed_at',
               existing_comment='处理完成时间',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.add_column('plugins', sa.Column('downloads_count', sa.Integer(), nullable=False, comment='下载/安装次数（插件市场统计）'))
    op.add_column('plugins', sa.Column('rating', sa.Float(), nullable=True, comment='评分（1.0-5.0，插件市场）'))
    op.add_column('plugins', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分类标签（如 ["ai", "adapter", "openai"]）'))
    op.add_column('plugins', sa.Column('category', sa.String(), nullable=True, comment='插件分类（如 ai-model, productivity, analytics）'))
    op.add_column('plugins', sa.Column('screenshots', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='截图 URL 列表（插件市场展示）'))
    op.add_column('plugins', sa.Column('source_url', sa.String(), nullable=True, comment='插件源码仓库 URL（如 GitHub 地址）'))
    op.add_column('plugins', sa.Column('license', sa.String(), nullable=True, comment='开源许可证（如 MIT, Apache-2.0）'))
    op.alter_column('plugins', 'name',
               existing_type=sa.VARCHAR(),
               comment='插件唯一标识（如 novusai-anthropic-adapter）',
               existing_comment='插件唯一标识',
               existing_nullable=False)
    op.alter_column('plugins', 'plugin_type',
               existing_type=sa.VARCHAR(),
               comment='插件类型（adapter/tool/hook/api/composite）',
               existing_comment='插件类型',
               existing_nullable=False)
    op.alter_column('plugins', 'status',
               existing_type=sa.VARCHAR(),
               comment='插件状态（installed/enabled/disabled/error）',
               existing_comment='插件状态',
               existing_nullable=False)
    op.alter_column('plugins', 'entry_point',
               existing_type=sa.VARCHAR(),
               comment='入口点（如 app.plugins.anthropic.main.AnthropicPlugin）',
               existing_comment='入口点',
               existing_nullable=False)
    op.alter_column('plugins', 'manifest',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='完整 manifest.json 内容',
               existing_comment='manifest.json 内容',
               existing_nullable=True)
    op.alter_column('plugins', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='是否为系统内置插件（不可卸载/禁用）',
               existing_comment='是否为系统内置插件',
               existing_nullable=False)
    op.alter_column('plugins', 'required_permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='所需权限声明列表（如 ["db:read", "http:outbound"]）',
               existing_comment='所需权限声明列表',
               existing_nullable=True)
    op.alter_column('plugins', 'dependencies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='依赖声明（如 {"novusai-core": ">=1.0.0"}）',
               existing_comment='依赖声明',
               existing_nullable=True)
    op.alter_column('plugins', 'conflicts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='互斥插件列表（如 ["old-adapter"]）',
               existing_comment='互斥插件列表',
               existing_nullable=True)
    op.alter_column('plugins', 'platform_version',
               existing_type=sa.VARCHAR(),
               comment='最低平台版本要求（如 >=2.0.0）',
               existing_comment='最低平台版本要求',
               existing_nullable=True)
    op.alter_column('plugins', 'config_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='配置项 JSON Schema（用于前端动态表单渲染）',
               existing_comment='配置项 JSON Schema',
               existing_nullable=True)
    op.alter_column('plugins', 'icon',
               existing_type=sa.VARCHAR(),
               comment='插件图标（URL 或 Lucide 图标名）',
               existing_comment='插件图标',
               existing_nullable=True)
    op.alter_column('plugins', 'readme',
               existing_type=sa.TEXT(),
               comment='README 内容（Markdown）',
               existing_comment='README 内容',
               existing_nullable=True)
    op.alter_column('plugins', 'delete_level',
               existing_type=sa.VARCHAR(length=20),
               comment='删除层级: tenant=租户回收站, admin=管理端回收站',
               existing_comment='删除层级',
               existing_nullable=True)
    op.alter_column('tenant_plugins', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='租户自定义配置（覆盖插件默认配置）',
               existing_comment='租户自定义配置',
               existing_nullable=True)
    op.alter_column('tenant_plugins', 'delete_level',
               existing_type=sa.VARCHAR(length=20),
               comment='删除层级: tenant=租户回收站, admin=管理端回收站',
               existing_comment='删除层级',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_plugins', 'delete_level',
               existing_type=sa.VARCHAR(length=20),
               comment='删除层级',
               existing_comment='删除层级: tenant=租户回收站, admin=管理端回收站',
               existing_nullable=True)
    op.alter_column('tenant_plugins', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='租户自定义配置',
               existing_comment='租户自定义配置（覆盖插件默认配置）',
               existing_nullable=True)
    op.alter_column('plugins', 'delete_level',
               existing_type=sa.VARCHAR(length=20),
               comment='删除层级',
               existing_comment='删除层级: tenant=租户回收站, admin=管理端回收站',
               existing_nullable=True)
    op.alter_column('plugins', 'readme',
               existing_type=sa.TEXT(),
               comment='README 内容',
               existing_comment='README 内容（Markdown）',
               existing_nullable=True)
    op.alter_column('plugins', 'icon',
               existing_type=sa.VARCHAR(),
               comment='插件图标',
               existing_comment='插件图标（URL 或 Lucide 图标名）',
               existing_nullable=True)
    op.alter_column('plugins', 'config_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='配置项 JSON Schema',
               existing_comment='配置项 JSON Schema（用于前端动态表单渲染）',
               existing_nullable=True)
    op.alter_column('plugins', 'platform_version',
               existing_type=sa.VARCHAR(),
               comment='最低平台版本要求',
               existing_comment='最低平台版本要求（如 >=2.0.0）',
               existing_nullable=True)
    op.alter_column('plugins', 'conflicts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='互斥插件列表',
               existing_comment='互斥插件列表（如 ["old-adapter"]）',
               existing_nullable=True)
    op.alter_column('plugins', 'dependencies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='依赖声明',
               existing_comment='依赖声明（如 {"novusai-core": ">=1.0.0"}）',
               existing_nullable=True)
    op.alter_column('plugins', 'required_permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='所需权限声明列表',
               existing_comment='所需权限声明列表（如 ["db:read", "http:outbound"]）',
               existing_nullable=True)
    op.alter_column('plugins', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='是否为系统内置插件',
               existing_comment='是否为系统内置插件（不可卸载/禁用）',
               existing_nullable=False)
    op.alter_column('plugins', 'manifest',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='manifest.json 内容',
               existing_comment='完整 manifest.json 内容',
               existing_nullable=True)
    op.alter_column('plugins', 'entry_point',
               existing_type=sa.VARCHAR(),
               comment='入口点',
               existing_comment='入口点（如 app.plugins.anthropic.main.AnthropicPlugin）',
               existing_nullable=False)
    op.alter_column('plugins', 'status',
               existing_type=sa.VARCHAR(),
               comment='插件状态',
               existing_comment='插件状态（installed/enabled/disabled/error）',
               existing_nullable=False)
    op.alter_column('plugins', 'plugin_type',
               existing_type=sa.VARCHAR(),
               comment='插件类型',
               existing_comment='插件类型（adapter/tool/hook/api/composite）',
               existing_nullable=False)
    op.alter_column('plugins', 'name',
               existing_type=sa.VARCHAR(),
               comment='插件唯一标识',
               existing_comment='插件唯一标识（如 novusai-anthropic-adapter）',
               existing_nullable=False)
    op.drop_column('plugins', 'license')
    op.drop_column('plugins', 'source_url')
    op.drop_column('plugins', 'screenshots')
    op.drop_column('plugins', 'category')
    op.drop_column('plugins', 'tags')
    op.drop_column('plugins', 'rating')
    op.drop_column('plugins', 'downloads_count')
    op.alter_column('knowledge_documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'processing_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='处理完成时间',
               existing_comment='knowledge_base.document_model.processing_completed_at',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'processing_started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='处理开始时间',
               existing_comment='knowledge_base.document_model.processing_started_at',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'char_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='文档总字符数',
               existing_comment='knowledge_base.document_model.char_count',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='文档总 Token 数',
               existing_comment='knowledge_base.document_model.token_count',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='分块数量',
               existing_comment='knowledge_base.document_model.chunk_count',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='重试次数',
               existing_comment='knowledge_base.document_model.retry_count',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'error_stage',
               existing_type=sa.VARCHAR(length=20),
               comment='失败阶段',
               existing_comment='knowledge_base.document_model.error_stage',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_comment='knowledge_base.document_model.error_message',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               comment='处理状态',
               existing_comment='knowledge_base.document_model.status',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'metadata_extra',
               existing_type=sa.TEXT(),
               comment='扩展元数据',
               existing_comment='knowledge_base.document_model.metadata_extra',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'source_url',
               existing_type=sa.TEXT(),
               comment='网页来源 URL',
               existing_comment='knowledge_base.document_model.source_url',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='MD5 哈希',
               existing_comment='knowledge_base.document_model.file_hash',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'file_size',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='文件大小（字节）',
               existing_comment='knowledge_base.document_model.file_size',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'txt'::character varying"),
               comment='文件类型',
               existing_comment='knowledge_base.document_model.file_type',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'file_name',
               existing_type=sa.VARCHAR(length=500),
               comment='原始文件名',
               existing_comment='knowledge_base.document_model.file_name',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'attachment_id',
               existing_type=sa.INTEGER(),
               comment='附件 ID',
               existing_comment='knowledge_base.document_model.attachment_id',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'knowledge_base_id',
               existing_type=sa.INTEGER(),
               comment='知识库 ID',
               existing_comment='knowledge_base.document_model.knowledge_base_id',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               comment='状态',
               existing_comment='knowledge_base.model.status',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'total_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='原始文件总大小',
               existing_comment='knowledge_base.model.total_size_bytes',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'total_chunks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='分块总数',
               existing_comment='knowledge_base.model.total_chunks',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'document_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='文档总数',
               existing_comment='knowledge_base.model.document_count',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'score_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               comment='最低相似度阈值',
               existing_comment='knowledge_base.model.score_threshold',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'top_k',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               comment='默认返回数量',
               existing_comment='knowledge_base.model.top_k',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'search_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'hybrid'::character varying"),
               comment='检索模式',
               existing_comment='knowledge_base.model.search_mode',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'chunk_strategy',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'recursive'::character varying"),
               comment='分块策略',
               existing_comment='knowledge_base.model.chunk_strategy',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'chunk_overlap',
               existing_type=sa.INTEGER(),
               server_default=sa.text('50'),
               comment='分块重叠',
               existing_comment='knowledge_base.model.chunk_overlap',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'chunk_size',
               existing_type=sa.INTEGER(),
               server_default=sa.text('512'),
               comment='分块大小',
               existing_comment='knowledge_base.model.chunk_size',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'embedding_dimensions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1536'),
               comment='向量维度',
               existing_comment='knowledge_base.model.embedding_dimensions',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'embedding_model_id',
               existing_type=sa.INTEGER(),
               comment='Embedding 模型 ID',
               existing_comment='knowledge_base.model.embedding_model_id',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'avatar',
               existing_type=sa.VARCHAR(length=50),
               comment='图标/颜色标识',
               existing_comment='knowledge_base.model.avatar',
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'description',
               existing_type=sa.TEXT(),
               comment='描述',
               existing_comment='knowledge_base.model.description',
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='知识库名称',
               existing_comment='knowledge_base.model.name',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'scope',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'tenant'::character varying"),
               comment=None,
               existing_comment='knowledge_base.model.scope',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_comment='租户ID（scope=tenant 时必填，global/admin_only 时为 NULL）',
               existing_nullable=True)
    op.add_column('document_chunks', sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, content)", persisted=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_document_chunks_knowledge_base_id'), table_name='document_chunks')
    op.create_index(op.f('ix_chunk_tsv'), 'document_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_chunk_embedding'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.alter_column('document_chunks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('document_chunks', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='元数据',
               existing_comment='knowledge_base.chunk_model.metadata',
               existing_nullable=True)
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment=None,
               existing_comment='knowledge_base.chunk_model.embedding',
               existing_nullable=True)
    op.alter_column('document_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='Token 数',
               existing_comment='knowledge_base.chunk_model.token_count',
               existing_nullable=False)
    op.alter_column('document_chunks', 'char_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='字符数',
               existing_comment='knowledge_base.chunk_model.char_count',
               existing_nullable=False)
    op.alter_column('document_chunks', 'content_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='内容 MD5',
               existing_comment='knowledge_base.chunk_model.content_hash',
               existing_nullable=False)
    op.alter_column('document_chunks', 'content',
               existing_type=sa.TEXT(),
               comment='分块文本内容',
               existing_comment='knowledge_base.chunk_model.content',
               existing_nullable=False)
    op.alter_column('document_chunks', 'chunk_index',
               existing_type=sa.INTEGER(),
               comment='块序号',
               existing_comment='knowledge_base.chunk_model.chunk_index',
               existing_nullable=False)
    op.alter_column('document_chunks', 'knowledge_base_id',
               existing_type=sa.INTEGER(),
               comment='知识库 ID',
               existing_comment='knowledge_base.chunk_model.knowledge_base_id',
               existing_nullable=False)
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.INTEGER(),
               comment='文档 ID',
               existing_comment='knowledge_base.chunk_model.document_id',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'duration_ms',
               existing_type=sa.INTEGER(),
               comment='执行耗时（毫秒）',
               existing_comment='ai_action_log.field.duration_ms',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_comment='ai_action_log.field.error_message',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='执行状态',
               existing_comment='ai_action_log.field.status',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'response_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='响应数据',
               existing_comment='ai_action_log.field.response_data',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'request_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='请求数据',
               existing_comment='ai_action_log.field.request_data',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'action_level',
               existing_type=sa.VARCHAR(length=50),
               comment='安全等级',
               existing_comment='ai_action_log.field.action_level',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'action_type',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型',
               existing_comment='ai_action_log.field.action_type',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'action_name',
               existing_type=sa.VARCHAR(length=100),
               comment='操作名称',
               existing_comment='ai_action_log.field.action_name',
               existing_nullable=False)
    op.alter_column('ai_action_logs', 'operator_id',
               existing_type=sa.INTEGER(),
               comment='操作者 ID',
               existing_comment='ai_action_log.field.operator_id',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment='对话 ID',
               existing_comment='ai_action_log.field.conversation_id',
               existing_nullable=True)
    op.alter_column('ai_action_logs', 'agent_id',
               existing_type=sa.INTEGER(),
               comment='智能体 ID',
               existing_comment='ai_action_log.field.agent_id',
               existing_nullable=False)
    op.alter_column('agents', 'rag_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='RAG 配置',
               existing_comment='enum.agent_model.rag_config',
               existing_nullable=True)
    op.alter_column('agents', 'knowledge_base_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='关联知识库 ID 列表',
               existing_comment='enum.agent_model.knowledge_base_ids',
               existing_nullable=True)
    op.alter_column('agents', 'scope',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'tenant'::character varying"),
               comment=None,
               existing_comment='enum.agent_model.scope',
               existing_nullable=False)
    op.alter_column('agents', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_comment='租户ID（scope=tenant 时必填，global/admin_only 时为 NULL）',
               existing_nullable=True)
    op.alter_column('agent_versions', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='agent.version.field.output_schema',
               existing_nullable=True)
    op.alter_column('agent_versions', 'context_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='agent.version.field.context_config',
               existing_nullable=True)
    op.alter_column('agent_versions', 'rag_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='agent.version.field.rag_config',
               existing_nullable=True)
    # ### end Alembic commands ###
