"""add email_logs table

Revision ID: fbe521b42f77
Revises: 20260221_seed_all
Create Date: 2026-02-20 22:33:46.158935+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbe521b42f77'
down_revision: Union[str, None] = '20260221_seed_all'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('to_address', sa.String(), nullable=False, comment='收件人（逗号分隔）'),
    sa.Column('cc', sa.String(), nullable=True, comment='抄送（逗号分隔）'),
    sa.Column('bcc', sa.String(), nullable=True, comment='密送（逗号分隔）'),
    sa.Column('subject', sa.String(), nullable=False, comment='邮件主题'),
    sa.Column('status', sa.String(), nullable=False, comment='发送状态（pending/sent/failed）'),
    sa.Column('triggered_by', sa.String(), nullable=False, comment='触发来源（manual/task_failure/password_reset/test/welcome/ssl_expiry）'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='实际发送时间'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='关联企业ID（可选）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.String(length=20), nullable=True, comment='删除层级: tenant=企业回收站, admin=管理端回收站'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_is_deleted'), 'email_logs', ['is_deleted'], unique=False)
    op.create_index('ix_email_logs_status', 'email_logs', ['status'], unique=False)
    op.create_index('ix_email_logs_tenant_id', 'email_logs', ['tenant_id'], unique=False)
    op.create_index('ix_email_logs_triggered_by', 'email_logs', ['triggered_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_logs_triggered_by', table_name='email_logs')
    op.drop_index('ix_email_logs_tenant_id', table_name='email_logs')
    op.drop_index('ix_email_logs_status', table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_is_deleted'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
