"""add_plugin_install_source_and_marketplace_slug

Revision ID: 31167c90d628
Revises: 75773a96dac5
Create Date: 2026-02-22 04:53:33.969746+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31167c90d628'
down_revision: Union[str, None] = '75773a96dac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugins', sa.Column('install_source', sa.String(), nullable=True, comment='安装来源（local/marketplace/builtin/entry_point）'))
    op.add_column('plugins', sa.Column('marketplace_slug', sa.String(), nullable=True, comment='插件市场 slug（市场安装时填写，用于后续升级匹配）'))
    # ### end Alembic commands ###

    # Data migration: set defaults for existing plugins
    op.execute("UPDATE plugins SET install_source = 'builtin' WHERE is_system = true AND install_source IS NULL")
    op.execute("UPDATE plugins SET install_source = 'local' WHERE is_system = false AND install_source IS NULL")


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugins', 'marketplace_slug')
    op.drop_column('plugins', 'install_source')
    # ### end Alembic commands ###
