"""add ai_action_logs table

Revision ID: ee87f790553e
Revises: 20260210_0009
Create Date: 2026-02-11 15:29:47.518054+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee87f790553e'
down_revision: Union[str, None] = '20260210_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_action_logs',
    sa.Column('agent_id', sa.Integer(), nullable=False, comment='智能体 ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=True, comment='对话 ID'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作者 ID'),
    sa.Column('action_name', sa.String(length=100), nullable=False, comment='操作名称'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='操作类型'),
    sa.Column('action_level', sa.String(length=50), nullable=False, comment='安全等级'),
    sa.Column('request_data', sa.JSON(), nullable=True, comment='请求数据'),
    sa.Column('response_data', sa.JSON(), nullable=True, comment='响应数据'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='执行状态'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='执行耗时（毫秒）'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_action_logs_operator_created', 'ai_action_logs', ['operator_id', 'created_at'], unique=False)
    op.create_index('idx_ai_action_logs_tenant_created', 'ai_action_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_ai_action_logs_type_created', 'ai_action_logs', ['action_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_action_logs_action_name'), 'ai_action_logs', ['action_name'], unique=False)
    op.create_index(op.f('ix_ai_action_logs_agent_id'), 'ai_action_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_ai_action_logs_conversation_id'), 'ai_action_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_action_logs_id'), 'ai_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_action_logs_is_deleted'), 'ai_action_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_action_logs_operator_id'), 'ai_action_logs', ['operator_id'], unique=False)
    op.create_index(op.f('ix_ai_action_logs_status'), 'ai_action_logs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_action_logs_tenant_id'), 'ai_action_logs', ['tenant_id'], unique=False)
    op.alter_column('agent_access', 'agent_id',
               existing_type=sa.INTEGER(),
               comment='agent_access.agent_id',
               existing_nullable=False)
    op.alter_column('agent_access', 'access_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='agent_access.access_type',
               existing_nullable=False)
    op.alter_column('agent_access', 'org_node_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='agent_access.org_node_ids',
               existing_nullable=True)
    op.alter_column('agent_access', 'user_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='agent_access.user_ids',
               existing_nullable=True)
    op.alter_column('agent_access', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('agent_access', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_access', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('agent_access', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='软删除标记',
               existing_nullable=False)
    op.create_index(op.f('ix_agent_access_id'), 'agent_access', ['id'], unique=False)
    op.create_index(op.f('ix_agent_access_is_deleted'), 'agent_access', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('agent_access_tenant_id_fkey'), 'agent_access', type_='foreignkey')
    op.alter_column('agent_conversations', 'agent_id',
               existing_type=sa.INTEGER(),
               comment='enum.agent_conversation.agent_id',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'user_id',
               existing_type=sa.INTEGER(),
               comment='enum.agent_conversation.user_id',
               existing_nullable=True)
    op.alter_column('agent_conversations', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='enum.agent_conversation.title',
               existing_nullable=True)
    op.alter_column('agent_conversations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='enum.agent_conversation.status',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_conversation.messages',
               existing_nullable=True)
    op.alter_column('agent_conversations', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='enum.agent_conversation.message_count',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='enum.agent_conversation.token_count',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'total_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='enum.agent_conversation.total_tokens',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=None,
               comment='enum.agent_conversation.cost',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_conversation.metadata',
               existing_nullable=True)
    op.alter_column('agent_conversations', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='软删除标记',
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_conv_agent_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conv_is_deleted'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conv_status'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conv_tenant_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conv_user_id'), table_name='agent_conversations')
    op.create_index(op.f('ix_agent_conversations_agent_id'), 'agent_conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_id'), 'agent_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_is_deleted'), 'agent_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agent_conversations_status'), 'agent_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_agent_conversations_tenant_id'), 'agent_conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_conversations_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.alter_column('agent_versions', 'agent_id',
               existing_type=sa.INTEGER(),
               comment='智能体 ID',
               existing_nullable=False)
    op.alter_column('agent_versions', 'version',
               existing_type=sa.INTEGER(),
               comment='版本号',
               existing_nullable=False)
    op.alter_column('agent_versions', 'system_prompt',
               existing_type=sa.TEXT(),
               comment='系统提示词',
               existing_nullable=False)
    op.alter_column('agent_versions', 'model_id',
               existing_type=sa.INTEGER(),
               comment='模型 ID',
               existing_nullable=False)
    op.alter_column('agent_versions', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='温度',
               existing_nullable=False)
    op.alter_column('agent_versions', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment='最大 Token',
               existing_nullable=True)
    op.alter_column('agent_versions', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Top P',
               existing_nullable=True)
    op.alter_column('agent_versions', 'execution_mode',
               existing_type=sa.VARCHAR(length=20),
               comment='执行模式',
               existing_nullable=False)
    op.alter_column('agent_versions', 'tool_bindings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='工具绑定',
               existing_nullable=True)
    op.alter_column('agent_versions', 'input_variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='输入变量',
               existing_nullable=True)
    op.alter_column('agent_versions', 'welcome_message',
               existing_type=sa.TEXT(),
               comment='欢迎语',
               existing_nullable=True)
    op.alter_column('agent_versions', 'suggested_questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='推荐问题',
               existing_nullable=True)
    op.alter_column('agent_versions', 'quota_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='配额配置',
               existing_nullable=True)
    op.alter_column('agent_versions', 'change_log',
               existing_type=sa.TEXT(),
               comment='变更说明',
               existing_nullable=True)
    op.alter_column('agent_versions', 'created_by',
               existing_type=sa.INTEGER(),
               comment='发布人',
               existing_nullable=True)
    op.alter_column('agent_versions', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('agent_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('agent_versions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='软删除标记',
               existing_nullable=False)
    op.create_index(op.f('ix_agent_versions_id'), 'agent_versions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_versions_is_deleted'), 'agent_versions', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('agent_versions_tenant_id_fkey'), 'agent_versions', type_='foreignkey')
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='enum.agent_model.name',
               existing_nullable=False)
    op.alter_column('agents', 'description',
               existing_type=sa.TEXT(),
               comment='enum.agent_model.description',
               existing_nullable=True)
    op.alter_column('agents', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               comment='enum.agent_model.avatar',
               existing_nullable=True)
    op.alter_column('agents', 'model_id',
               existing_type=sa.INTEGER(),
               comment='enum.agent_model.model_id',
               existing_nullable=False)
    op.alter_column('agents', 'system_prompt',
               existing_type=sa.TEXT(),
               comment='enum.agent_model.system_prompt',
               existing_nullable=False)
    op.alter_column('agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               comment='enum.agent_model.temperature',
               existing_nullable=False)
    op.alter_column('agents', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment='enum.agent_model.max_tokens',
               existing_nullable=True)
    op.alter_column('agents', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='enum.agent_model.top_p',
               existing_nullable=True)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='enum.agent_model.status',
               existing_nullable=False)
    op.alter_column('agents', 'execution_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='enum.agent_model.execution_mode',
               existing_nullable=False)
    op.alter_column('agents', 'published_version',
               existing_type=sa.INTEGER(),
               comment='enum.agent_model.published_version',
               existing_nullable=True)
    op.alter_column('agents', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='enum.agent_model.visibility',
               existing_nullable=False)
    op.alter_column('agents', 'quota_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_model.quota_config',
               existing_comment='智能体配额配置',
               existing_nullable=True)
    op.alter_column('agents', 'tool_bindings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_model.tool_bindings',
               existing_nullable=True)
    op.alter_column('agents', 'input_variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_model.input_variables',
               existing_nullable=True)
    op.alter_column('agents', 'context_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_model.context_config',
               existing_nullable=True)
    op.alter_column('agents', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_model.output_schema',
               existing_nullable=True)
    op.alter_column('agents', 'welcome_message',
               existing_type=sa.TEXT(),
               comment='enum.agent_model.welcome_message',
               existing_nullable=True)
    op.alter_column('agents', 'suggested_questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.agent_model.suggested_questions',
               existing_nullable=True)
    op.alter_column('agents', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('agents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='软删除标记',
               existing_nullable=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.alter_column('batch_runs', 'agent_id',
               existing_type=sa.INTEGER(),
               comment='enum.batch_run.agent_id',
               existing_nullable=False)
    op.alter_column('batch_runs', 'created_by',
               existing_type=sa.INTEGER(),
               comment='enum.batch_run.created_by',
               existing_nullable=True)
    op.alter_column('batch_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='enum.batch_run.status',
               existing_nullable=False)
    op.alter_column('batch_runs', 'total_items',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='enum.batch_run.total_items',
               existing_nullable=False)
    op.alter_column('batch_runs', 'completed_items',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='enum.batch_run.completed_items',
               existing_nullable=False)
    op.alter_column('batch_runs', 'failed_items',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='enum.batch_run.failed_items',
               existing_nullable=False)
    op.alter_column('batch_runs', 'max_workers',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='enum.batch_run.max_workers',
               existing_nullable=False)
    op.alter_column('batch_runs', 'results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.batch_run.results',
               existing_nullable=True)
    op.alter_column('batch_runs', 'errors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.batch_run.errors',
               existing_nullable=True)
    op.alter_column('batch_runs', 'input_items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.batch_run.input_items',
               existing_nullable=True)
    op.alter_column('batch_runs', 'celery_task_id',
               existing_type=sa.VARCHAR(length=64),
               comment='enum.batch_run.celery_task_id',
               existing_nullable=True)
    op.alter_column('batch_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='enum.batch_run.started_at',
               existing_nullable=True)
    op.alter_column('batch_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='enum.batch_run.completed_at',
               existing_nullable=True)
    op.alter_column('batch_runs', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('batch_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('batch_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('batch_runs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='软删除标记',
               existing_nullable=False)
    op.create_index(op.f('ix_batch_runs_id'), 'batch_runs', ['id'], unique=False)
    op.alter_column('conversation_messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment='enum.conversation_message.conversation_id',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='enum.conversation_message.role',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'content',
               existing_type=sa.TEXT(),
               comment='enum.conversation_message.content',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'sequence',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='enum.conversation_message.sequence',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='enum.conversation_message.token_count',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'tool_calls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.conversation_message.tool_calls',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'tool_call_id',
               existing_type=sa.VARCHAR(length=100),
               comment='enum.conversation_message.tool_call_id',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'tool_name',
               existing_type=sa.VARCHAR(length=100),
               comment='enum.conversation_message.tool_name',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment='enum.conversation_message.latency_ms',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'model_id',
               existing_type=sa.INTEGER(),
               comment='enum.conversation_message.model_id',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='enum.conversation_message.metadata',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='软删除标记',
               existing_nullable=False)
    op.drop_index(op.f('ix_conv_msg_conversation_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conv_msg_is_deleted'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conv_msg_role'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conv_msg_tenant_id'), table_name='conversation_messages')
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_is_deleted'), 'conversation_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_conversation_messages_role'), 'conversation_messages', ['role'], unique=False)
    op.create_index(op.f('ix_conversation_messages_tenant_id'), 'conversation_messages', ['tenant_id'], unique=False)
    op.alter_column('tool_definitions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='工具名称',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'description',
               existing_type=sa.TEXT(),
               comment='工具描述',
               existing_nullable=True)
    op.alter_column('tool_definitions', 'type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='工具类型',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'input_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='输入 Schema',
               existing_nullable=True)
    op.alter_column('tool_definitions', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='输出 Schema',
               existing_nullable=True)
    op.alter_column('tool_definitions', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='执行配置',
               existing_nullable=True)
    op.alter_column('tool_definitions', 'timeout',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='超时时间',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='系统工具',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='启用状态',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='软删除标记',
               existing_nullable=False)
    op.drop_index(op.f('ix_tool_defs_is_deleted'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_defs_is_system'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_defs_name'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_defs_tenant_id'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_defs_type'), table_name='tool_definitions')
    op.create_index(op.f('ix_tool_definitions_id'), 'tool_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_tool_definitions_is_deleted'), 'tool_definitions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tool_definitions_is_system'), 'tool_definitions', ['is_system'], unique=False)
    op.create_index(op.f('ix_tool_definitions_name'), 'tool_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_tool_definitions_tenant_id'), 'tool_definitions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_definitions_type'), 'tool_definitions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_definitions_type'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_tenant_id'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_name'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_is_system'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_is_deleted'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_id'), table_name='tool_definitions')
    op.create_index(op.f('ix_tool_defs_type'), 'tool_definitions', ['type'], unique=False)
    op.create_index(op.f('ix_tool_defs_tenant_id'), 'tool_definitions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_defs_name'), 'tool_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_tool_defs_is_system'), 'tool_definitions', ['is_system'], unique=False)
    op.create_index(op.f('ix_tool_defs_is_deleted'), 'tool_definitions', ['is_deleted'], unique=False)
    op.alter_column('tool_definitions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='启用状态',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='系统工具',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'timeout',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               comment=None,
               existing_comment='超时时间',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='执行配置',
               existing_nullable=True)
    op.alter_column('tool_definitions', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='输出 Schema',
               existing_nullable=True)
    op.alter_column('tool_definitions', 'input_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='输入 Schema',
               existing_nullable=True)
    op.alter_column('tool_definitions', 'type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'http'::character varying"),
               comment=None,
               existing_comment='工具类型',
               existing_nullable=False)
    op.alter_column('tool_definitions', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='工具描述',
               existing_nullable=True)
    op.alter_column('tool_definitions', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='工具名称',
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_messages_tenant_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_role'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_is_deleted'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.create_index(op.f('ix_conv_msg_tenant_id'), 'conversation_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_conv_msg_role'), 'conversation_messages', ['role'], unique=False)
    op.create_index(op.f('ix_conv_msg_is_deleted'), 'conversation_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_conv_msg_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.alter_column('conversation_messages', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.conversation_message.metadata',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.conversation_message.model_id',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.conversation_message.latency_ms',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'tool_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='enum.conversation_message.tool_name',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'tool_call_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='enum.conversation_message.tool_call_id',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'tool_calls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.conversation_message.tool_calls',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='enum.conversation_message.token_count',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'sequence',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='enum.conversation_message.sequence',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='enum.conversation_message.content',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'user'::character varying"),
               comment=None,
               existing_comment='enum.conversation_message.role',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.conversation_message.conversation_id',
               existing_nullable=False)
    op.drop_index(op.f('ix_batch_runs_id'), table_name='batch_runs')
    op.alter_column('batch_runs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('batch_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('batch_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('batch_runs', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('batch_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='enum.batch_run.completed_at',
               existing_nullable=True)
    op.alter_column('batch_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='enum.batch_run.started_at',
               existing_nullable=True)
    op.alter_column('batch_runs', 'celery_task_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='enum.batch_run.celery_task_id',
               existing_nullable=True)
    op.alter_column('batch_runs', 'input_items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.batch_run.input_items',
               existing_nullable=True)
    op.alter_column('batch_runs', 'errors',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.batch_run.errors',
               existing_nullable=True)
    op.alter_column('batch_runs', 'results',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.batch_run.results',
               existing_nullable=True)
    op.alter_column('batch_runs', 'max_workers',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               comment=None,
               existing_comment='enum.batch_run.max_workers',
               existing_nullable=False)
    op.alter_column('batch_runs', 'failed_items',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='enum.batch_run.failed_items',
               existing_nullable=False)
    op.alter_column('batch_runs', 'completed_items',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='enum.batch_run.completed_items',
               existing_nullable=False)
    op.alter_column('batch_runs', 'total_items',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='enum.batch_run.total_items',
               existing_nullable=False)
    op.alter_column('batch_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               comment=None,
               existing_comment='enum.batch_run.status',
               existing_nullable=False)
    op.alter_column('batch_runs', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.batch_run.created_by',
               existing_nullable=True)
    op.alter_column('batch_runs', 'agent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.batch_run.agent_id',
               existing_nullable=False)
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.alter_column('agents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('agents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('agents', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('agents', 'suggested_questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.agent_model.suggested_questions',
               existing_nullable=True)
    op.alter_column('agents', 'welcome_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='enum.agent_model.welcome_message',
               existing_nullable=True)
    op.alter_column('agents', 'output_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.agent_model.output_schema',
               existing_nullable=True)
    op.alter_column('agents', 'context_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.agent_model.context_config',
               existing_nullable=True)
    op.alter_column('agents', 'input_variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.agent_model.input_variables',
               existing_nullable=True)
    op.alter_column('agents', 'tool_bindings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.agent_model.tool_bindings',
               existing_nullable=True)
    op.alter_column('agents', 'quota_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='智能体配额配置',
               existing_comment='enum.agent_model.quota_config',
               existing_nullable=True)
    op.alter_column('agents', 'visibility',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'public'::character varying"),
               comment=None,
               existing_comment='enum.agent_model.visibility',
               existing_nullable=False)
    op.alter_column('agents', 'published_version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.agent_model.published_version',
               existing_nullable=True)
    op.alter_column('agents', 'execution_mode',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'conversation'::character varying"),
               comment=None,
               existing_comment='enum.agent_model.execution_mode',
               existing_nullable=False)
    op.alter_column('agents', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'draft'::character varying"),
               comment=None,
               existing_comment='enum.agent_model.status',
               existing_nullable=False)
    op.alter_column('agents', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='enum.agent_model.top_p',
               existing_nullable=True)
    op.alter_column('agents', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.agent_model.max_tokens',
               existing_nullable=True)
    op.alter_column('agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.7'::double precision"),
               comment=None,
               existing_comment='enum.agent_model.temperature',
               existing_nullable=False)
    op.alter_column('agents', 'system_prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='enum.agent_model.system_prompt',
               existing_nullable=False)
    op.alter_column('agents', 'model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.agent_model.model_id',
               existing_nullable=False)
    op.alter_column('agents', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='enum.agent_model.avatar',
               existing_nullable=True)
    op.alter_column('agents', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='enum.agent_model.description',
               existing_nullable=True)
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='enum.agent_model.name',
               existing_nullable=False)
    op.create_foreign_key(op.f('agent_versions_tenant_id_fkey'), 'agent_versions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_versions_is_deleted'), table_name='agent_versions')
    op.drop_index(op.f('ix_agent_versions_id'), table_name='agent_versions')
    op.alter_column('agent_versions', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('agent_versions', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('agent_versions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_versions', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('agent_versions', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='发布人',
               existing_nullable=True)
    op.alter_column('agent_versions', 'change_log',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='变更说明',
               existing_nullable=True)
    op.alter_column('agent_versions', 'quota_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='配额配置',
               existing_nullable=True)
    op.alter_column('agent_versions', 'suggested_questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='推荐问题',
               existing_nullable=True)
    op.alter_column('agent_versions', 'welcome_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='欢迎语',
               existing_nullable=True)
    op.alter_column('agent_versions', 'input_variables',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='输入变量',
               existing_nullable=True)
    op.alter_column('agent_versions', 'tool_bindings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='工具绑定',
               existing_nullable=True)
    op.alter_column('agent_versions', 'execution_mode',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='执行模式',
               existing_nullable=False)
    op.alter_column('agent_versions', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Top P',
               existing_nullable=True)
    op.alter_column('agent_versions', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='最大 Token',
               existing_nullable=True)
    op.alter_column('agent_versions', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.7'::double precision"),
               comment=None,
               existing_comment='温度',
               existing_nullable=False)
    op.alter_column('agent_versions', 'model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='模型 ID',
               existing_nullable=False)
    op.alter_column('agent_versions', 'system_prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='系统提示词',
               existing_nullable=False)
    op.alter_column('agent_versions', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='版本号',
               existing_nullable=False)
    op.alter_column('agent_versions', 'agent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='智能体 ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_conversations_user_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_tenant_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_status'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_is_deleted'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_id'), table_name='agent_conversations')
    op.drop_index(op.f('ix_agent_conversations_agent_id'), table_name='agent_conversations')
    op.create_index(op.f('ix_agent_conv_user_id'), 'agent_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_conv_tenant_id'), 'agent_conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agent_conv_status'), 'agent_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_agent_conv_is_deleted'), 'agent_conversations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_agent_conv_agent_id'), 'agent_conversations', ['agent_id'], unique=False)
    op.alter_column('agent_conversations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.agent_conversation.metadata',
               existing_nullable=True)
    op.alter_column('agent_conversations', 'cost',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=sa.text("'0'::numeric"),
               comment=None,
               existing_comment='enum.agent_conversation.cost',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'total_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='enum.agent_conversation.total_tokens',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'token_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='enum.agent_conversation.token_count',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment=None,
               existing_comment='enum.agent_conversation.message_count',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='enum.agent_conversation.messages',
               existing_nullable=True)
    op.alter_column('agent_conversations', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               comment=None,
               existing_comment='enum.agent_conversation.status',
               existing_nullable=False)
    op.alter_column('agent_conversations', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='enum.agent_conversation.title',
               existing_nullable=True)
    op.alter_column('agent_conversations', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.agent_conversation.user_id',
               existing_nullable=True)
    op.alter_column('agent_conversations', 'agent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='enum.agent_conversation.agent_id',
               existing_nullable=False)
    op.create_foreign_key(op.f('agent_access_tenant_id_fkey'), 'agent_access', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_access_is_deleted'), table_name='agent_access')
    op.drop_index(op.f('ix_agent_access_id'), table_name='agent_access')
    op.alter_column('agent_access', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='软删除标记',
               existing_nullable=False)
    op.alter_column('agent_access', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('agent_access', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('agent_access', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('agent_access', 'user_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='agent_access.user_ids',
               existing_nullable=True)
    op.alter_column('agent_access', 'org_node_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='agent_access.org_node_ids',
               existing_nullable=True)
    op.alter_column('agent_access', 'access_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'all_users'::character varying"),
               comment=None,
               existing_comment='agent_access.access_type',
               existing_nullable=False)
    op.alter_column('agent_access', 'agent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='agent_access.agent_id',
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_action_logs_tenant_id'), table_name='ai_action_logs')
    op.drop_index(op.f('ix_ai_action_logs_status'), table_name='ai_action_logs')
    op.drop_index(op.f('ix_ai_action_logs_operator_id'), table_name='ai_action_logs')
    op.drop_index(op.f('ix_ai_action_logs_is_deleted'), table_name='ai_action_logs')
    op.drop_index(op.f('ix_ai_action_logs_id'), table_name='ai_action_logs')
    op.drop_index(op.f('ix_ai_action_logs_conversation_id'), table_name='ai_action_logs')
    op.drop_index(op.f('ix_ai_action_logs_agent_id'), table_name='ai_action_logs')
    op.drop_index(op.f('ix_ai_action_logs_action_name'), table_name='ai_action_logs')
    op.drop_index('idx_ai_action_logs_type_created', table_name='ai_action_logs')
    op.drop_index('idx_ai_action_logs_tenant_created', table_name='ai_action_logs')
    op.drop_index('idx_ai_action_logs_operator_created', table_name='ai_action_logs')
    op.drop_table('ai_action_logs')
    # ### end Alembic commands ###
