"""add_skills_table

Revision ID: 63eadfe34156
Revises: 8c70188e6307
Create Date: 2026-02-13 10:56:51.353389+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63eadfe34156'
down_revision: Union[str, None] = '8c70188e6307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='企业ID（scope=tenant 时必填，scope=admin 时为 NULL）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='技能名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='技能描述'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='技能图标'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='技能类型'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='作用域'),
    sa.Column('config', sa.JSON(), nullable=True, comment='技能配置'),
    sa.Column('input_schema', sa.JSON(), nullable=True, comment='输入 Schema'),
    sa.Column('output_schema', sa.JSON(), nullable=True, comment='输出 Schema'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='启用状态'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='超时时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('delete_level', sa.String(length=20), nullable=True, comment='删除层级: tenant=企业回收站, admin=管理端回收站'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_is_deleted'), 'skills', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_index(op.f('ix_skills_scope'), 'skills', ['scope'], unique=False)
    op.create_index('ix_skills_tenant_active', 'skills', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_skills_tenant_id'), 'skills', ['tenant_id'], unique=False)
    op.create_index('ix_skills_tenant_scope', 'skills', ['tenant_id', 'scope'], unique=False)
    op.create_index('ix_skills_tenant_type', 'skills', ['tenant_id', 'type'], unique=False)
    op.create_index(op.f('ix_skills_type'), 'skills', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_type'), table_name='skills')
    op.drop_index('ix_skills_tenant_type', table_name='skills')
    op.drop_index('ix_skills_tenant_scope', table_name='skills')
    op.drop_index(op.f('ix_skills_tenant_id'), table_name='skills')
    op.drop_index('ix_skills_tenant_active', table_name='skills')
    op.drop_index(op.f('ix_skills_scope'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_deleted'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
