"""add_system_config_tables

Revision ID: 3f669a3f2342
Revises: 0006_org_root
Create Date: 2026-01-16 16:00:16.536070+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f669a3f2342'
down_revision: Union[str, None] = '0006_org_root'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config_groups',
    sa.Column('code', sa.String(length=100), nullable=False, comment='分组代码（唯一标识）'),
    sa.Column('name_key', sa.String(length=200), nullable=False, comment='名称的 i18n 键'),
    sa.Column('description_key', sa.String(length=200), nullable=True, comment='描述的 i18n 键'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='作用域: platform/tenant'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分组 ID'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='分组图标'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序顺序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['parent_id'], ['system_config_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_groups_code'), 'system_config_groups', ['code'], unique=True)
    op.create_index(op.f('ix_system_config_groups_id'), 'system_config_groups', ['id'], unique=False)
    op.create_index(op.f('ix_system_config_groups_is_deleted'), 'system_config_groups', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_config_groups_parent_id'), 'system_config_groups', ['parent_id'], unique=False)
    op.create_index(op.f('ix_system_config_groups_scope'), 'system_config_groups', ['scope'], unique=False)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键名'),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='所属分组 ID'),
    sa.Column('name_key', sa.String(length=200), nullable=False, comment='名称的 i18n 键'),
    sa.Column('description_key', sa.String(length=200), nullable=True, comment='描述的 i18n 键'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='作用域: platform/tenant'),
    sa.Column('value_type', sa.String(length=20), nullable=False, comment='值类型: string/number/boolean/select/multi_select/json/text/password/color/image'),
    sa.Column('default_value', sa.Text(), nullable=True, comment='默认值（JSON 字符串存储）'),
    sa.Column('validation_rules', sa.Text(), nullable=True, comment='验证规则（JSON 格式）'),
    sa.Column('options', sa.Text(), nullable=True, comment='选项列表（用于 select/multi_select，JSON 格式）'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='是否必填'),
    sa.Column('is_visible', sa.Boolean(), nullable=False, comment='是否在配置界面显示'),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False, comment='是否加密存储'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序顺序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['group_id'], ['system_config_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_group_id'), 'system_configs', ['group_id'], unique=False)
    op.create_index('ix_system_configs_group_key', 'system_configs', ['group_id', 'key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_index(op.f('ix_system_configs_is_deleted'), 'system_configs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=False)
    op.create_index(op.f('ix_system_configs_scope'), 'system_configs', ['scope'], unique=False)
    op.create_table('system_config_values',
    sa.Column('config_id', sa.Integer(), nullable=False, comment='配置项 ID'),
    sa.Column('value', sa.Text(), nullable=True, comment='配置值（JSON 字符串存储）'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.ForeignKeyConstraint(['config_id'], ['system_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_values_config_id'), 'system_config_values', ['config_id'], unique=False)
    op.create_index('ix_system_config_values_config_tenant', 'system_config_values', ['config_id', 'tenant_id'], unique=True)
    op.create_index(op.f('ix_system_config_values_id'), 'system_config_values', ['id'], unique=False)
    op.create_index(op.f('ix_system_config_values_is_deleted'), 'system_config_values', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_config_values_tenant_id'), 'system_config_values', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_config_values_tenant_id'), table_name='system_config_values')
    op.drop_index(op.f('ix_system_config_values_is_deleted'), table_name='system_config_values')
    op.drop_index(op.f('ix_system_config_values_id'), table_name='system_config_values')
    op.drop_index('ix_system_config_values_config_tenant', table_name='system_config_values')
    op.drop_index(op.f('ix_system_config_values_config_id'), table_name='system_config_values')
    op.drop_table('system_config_values')
    op.drop_index(op.f('ix_system_configs_scope'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_is_deleted'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index('ix_system_configs_group_key', table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_group_id'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_system_config_groups_scope'), table_name='system_config_groups')
    op.drop_index(op.f('ix_system_config_groups_parent_id'), table_name='system_config_groups')
    op.drop_index(op.f('ix_system_config_groups_is_deleted'), table_name='system_config_groups')
    op.drop_index(op.f('ix_system_config_groups_id'), table_name='system_config_groups')
    op.drop_index(op.f('ix_system_config_groups_code'), table_name='system_config_groups')
    op.drop_table('system_config_groups')
    # ### end Alembic commands ###
