"""add_skill_consent_overrides_to_bindings

Revision ID: 61e838badbfa
Revises: e97db2eecd63
Create Date: 2026-02-21 03:28:55.973842+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e838badbfa'
down_revision: Union[str, None] = 'e97db2eecd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_skill_bindings', sa.Column('skill_consent_overrides', sa.JSON(), nullable=True, comment='agent_skill_binding.field.skill_consent_overrides'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_skill_bindings', 'skill_consent_overrides')
    # ### end Alembic commands ###
