/**
 * AI Panel state management / AI Panel 状态管理
 *
 * Manages AI slide panel global state: visibility, mode, active conversation,
 * pinned agent, interaction updates, etc. Replaces global-ai-chat.ts.
 * 管理 AI 侧滑面板的全局状态。
 */
import { ref } from 'vue';

import { defineStore } from 'pinia';

/** Panel display mode / 面板显示模式 */
export type AIPanelMode = 'full' | 'panel';

/** 页面上下文信息 / Page context payload */
export interface PageContext {
  available_apis: string[];
  locale: string;
  page_description: string;
  page_title: string;
  query_params: Record<string, string>;
  route_name: string;
  route_path: string;
}

/** 用户上下文信息 / User context payload */
export interface UserContext {
  current_time: string;
  user_nickname: string;
}

export interface AIInteractionUpdate {
  action?: string;
  auto_approved?: boolean;
  kind: 'action_buttons' | 'pending_confirmation' | 'pending_consent';
  rejected?: boolean;
  table?: string;
  tool_name?: string;
  value?: string;
}

export const useAIPanelStore = defineStore('ai-panel', () => {
  // ==================== Panel state / 面板状态 ====================

  /** Whether panel is visible / 面板是否可见 */
  const visible = ref(false);

  /** Panel mode: panel (slide) / full (fullscreen) / 面板模式 */
  const mode = ref<AIPanelMode>('panel');

  /** Whether panel is minimized to floating bubble / 面板是否最小化为浮动气泡 */
  const minimized = ref(false);

  /** Whether panel is docked (pushes main content; undocked closes on outside click) / 面板是否固定 */
  const docked = ref(true);

  /** Panel current width (for layout sync, updates on drag) / 面板当前宽度 */
  const panelWidth = ref(460);

  /** Whether AI chat surface may be opened / AI 对话面板是否允许打开 */
  const chatAvailable = ref(true);

  // ==================== Conversation state / 对话状态 ====================

  /** Active conversation ID (null = new conversation) / 活跃对话 ID */
  const activeConversationId = ref<null | number>(null);

  /** Current conversation's main agent ID (for list display) / 当前对话的主智能体 ID */
  const activeAgentId = ref<null | number>(null);

  // ==================== Pinned agent / 固定智能体（Pin） ====================

  /** User-pinned agent ID (bypasses routing, uses this agent directly) / 用户固定的智能体 ID */
  const pinnedAgentId = ref<null | number>(null);

  /** Pinned agent name (for UI display) / 固定的智能体名称 */
  const pinnedAgentName = ref<null | string>(null);

  // ==================== Pending state / 待消费状态 ====================

  /** Agent ID set by external page to open / 外部页面设置的待打开智能体 ID */
  const pendingAgentId = ref<number | undefined>(undefined);

  /** Pending external message to send after panel opens / 面板打开后待发送的外部消息 */
  const pendingMessage = ref<null | string>(null);

  /** Pending conversation to restore after panel opens / 面板打开后待恢复的对话 */
  const pendingConversationId = ref<null | number>(null);

  /** Whether there are unread messages / 是否有未读消息 */
  const hasUnread = ref(false);

  // ==================== Context state / 上下文状态 ====================

  /** Current page context (collected on panel open) / 当前页面上下文 */
  const pageContext = ref<null | PageContext>(null);

  /** Dynamic welcome message generated by LLM / LLM 生成的动态欢迎语 */
  const dynamicWelcomeMessage = ref<null | string>(null);

  /** Suggested actions from welcome generation / 欢迎语建议操作 */
  const welcomeSuggestedActions = ref<string[]>([]);

  // ==================== Panel actions / 面板操作 ====================

  function clearPendingContext() {
    pendingAgentId.value = undefined;
    pendingMessage.value = null;
    pendingConversationId.value = null;
    pageContext.value = null;
    dynamicWelcomeMessage.value = null;
    welcomeSuggestedActions.value = [];
  }

  function setPageContext(ctx: null | PageContext) {
    pageContext.value = ctx;
  }

  function setDynamicWelcome(
    welcomeMessage: null | string,
    suggestedActions: string[] = [],
  ) {
    dynamicWelcomeMessage.value = welcomeMessage;
    welcomeSuggestedActions.value = suggestedActions;
  }

  function clearDynamicWelcome() {
    dynamicWelcomeMessage.value = null;
    welcomeSuggestedActions.value = [];
  }

  function setChatAvailable(available: boolean) {
    chatAvailable.value = available;
    if (!available) {
      close();
      clearPendingContext();
      pendingInteractionUpdates.value = [];
    }
  }

  function open(): boolean {
    if (!chatAvailable.value) {
      clearPendingContext();
      return false;
    }
    visible.value = true;
    minimized.value = false;
    hasUnread.value = false;
    return true;
  }

  function close() {
    visible.value = false;
    minimized.value = false;
  }

  function toggle() {
    if (visible.value) {
      minimize();
    } else {
      open();
    }
  }

  function minimize() {
    visible.value = false;
    minimized.value = activeConversationId.value !== null;
  }

  function restore(): boolean {
    if (!chatAvailable.value) {
      clearPendingContext();
      return false;
    }
    visible.value = true;
    minimized.value = false;
    hasUnread.value = false;
    return true;
  }

  function setFullMode() {
    mode.value = 'full';
  }

  function setPanelMode() {
    mode.value = 'panel';
  }

  function toggleMode() {
    mode.value = mode.value === 'panel' ? 'full' : 'panel';
  }

  function toggleDock() {
    docked.value = !docked.value;
  }

  // ==================== Conversation actions / 对话操作 ====================

  function setConversation(conversationId: null | number, agentId?: number) {
    activeConversationId.value = conversationId;
    if (agentId !== undefined) {
      activeAgentId.value = agentId;
    }
  }

  function resetConversation() {
    activeConversationId.value = null;
    activeAgentId.value = null;
  }

  // ==================== Pin actions / Pin 操作 ====================

  function pinAgent(agentId: number, agentName: string) {
    pinnedAgentId.value = agentId;
    pinnedAgentName.value = agentName;
  }

  function unpinAgent() {
    pinnedAgentId.value = null;
    pinnedAgentName.value = null;
  }

  function togglePin(agentId: number, agentName: string) {
    if (pinnedAgentId.value === agentId) {
      unpinAgent();
    } else {
      pinAgent(agentId, agentName);
    }
  }

  // ==================== External entry / 外部入口 ====================

  /**
   * Open panel from external page and preselect agent
   * 从外部页面打开面板并预选智能体
   */
  function openWithAgent(agentId: number): boolean {
    if (!chatAvailable.value) {
      clearPendingContext();
      return false;
    }
    pendingAgentId.value = agentId;
    return open();
  }

  function queueMessage(message: null | string | undefined): boolean {
    if (!chatAvailable.value) {
      pendingMessage.value = null;
      return false;
    }
    const normalized = message?.trim();
    pendingMessage.value = normalized || null;
    return Boolean(pendingMessage.value);
  }

  function consumePendingMessage(): null | string {
    const message = pendingMessage.value;
    pendingMessage.value = null;
    return message;
  }

  function queueConversationRestore(
    conversationId: null | number | undefined,
  ): boolean {
    if (!chatAvailable.value) {
      pendingConversationId.value = null;
      return false;
    }
    pendingConversationId.value =
      typeof conversationId === 'number' && Number.isFinite(conversationId)
        ? conversationId
        : null;
    return pendingConversationId.value !== null;
  }

  function consumePendingConversationId(): null | number {
    const conversationId = pendingConversationId.value;
    pendingConversationId.value = null;
    return conversationId;
  }

  function openWithContext(options?: {
    agentId?: number;
    conversationId?: null | number;
    message?: null | string;
    pageContext?: null | PageContext;
  }): boolean {
    if (!chatAvailable.value) {
      close();
      clearPendingContext();
      return false;
    }
    if (
      typeof options?.agentId === 'number' &&
      Number.isFinite(options.agentId)
    ) {
      pendingAgentId.value = options.agentId;
    }
    if (options?.message !== undefined) {
      queueMessage(options.message);
    }
    if (options?.conversationId !== undefined) {
      queueConversationRestore(options.conversationId);
    }
    if (options?.pageContext !== undefined) {
      setPageContext(options.pageContext);
    }
    return open();
  }

  /**
   * Consume and clear pending agent ID / 消费并清除待使用的智能体 ID
   */
  function consumePendingAgentId(): number | undefined {
    const id = pendingAgentId.value;
    pendingAgentId.value = undefined;
    return id;
  }

  function markUnread() {
    if (!chatAvailable.value) {
      return;
    }
    if (!visible.value) {
      hasUnread.value = true;
    }
  }

  // ==================== Interaction confirmation / 交互确认 ====================

  const pendingInteractionUpdates = ref<AIInteractionUpdate[]>([]);

  function queueInteractionUpdate(update: AIInteractionUpdate) {
    if (!chatAvailable.value) {
      return;
    }
    pendingInteractionUpdates.value.push({ ...update });
  }

  function consumeInteractionUpdates(): AIInteractionUpdate[] {
    const updates = [...pendingInteractionUpdates.value];
    pendingInteractionUpdates.value = [];
    return updates;
  }

  function restoreInteractionUpdates(updates: AIInteractionUpdate[]) {
    if (!chatAvailable.value || updates.length === 0) return;
    pendingInteractionUpdates.value = [
      ...updates.map((item) => ({ ...item })),
      ...pendingInteractionUpdates.value,
    ];
  }

  // ==================== Reset / 重置 ====================

  function $reset() {
    visible.value = false;
    mode.value = 'panel';
    minimized.value = false;
    docked.value = true;
    panelWidth.value = 460;
    chatAvailable.value = true;
    activeConversationId.value = null;
    activeAgentId.value = null;
    pinnedAgentId.value = null;
    pinnedAgentName.value = null;
    pendingAgentId.value = undefined;
    pendingMessage.value = null;
    pendingConversationId.value = null;
    hasUnread.value = false;
    pendingInteractionUpdates.value = [];
    pageContext.value = null;
    dynamicWelcomeMessage.value = null;
    welcomeSuggestedActions.value = [];
  }

  return {
    // State / 状态
    visible,
    mode,
    minimized,
    docked,
    panelWidth,
    chatAvailable,
    activeConversationId,
    activeAgentId,
    pinnedAgentId,
    pinnedAgentName,
    pendingAgentId,
    pendingMessage,
    pendingConversationId,
    hasUnread,
    pageContext,
    dynamicWelcomeMessage,
    welcomeSuggestedActions,

    // Panel actions / 面板操作
    open,
    close,
    toggle,
    minimize,
    restore,
    setFullMode,
    setPanelMode,
    toggleMode,
    toggleDock,
    setChatAvailable,

    // Conversation / 会话
    setConversation,
    resetConversation,

    // Pin / 置顶
    pinAgent,
    unpinAgent,
    togglePin,

    // External / 外部
    clearPendingContext,
    openWithAgent,
    openWithContext,
    setPageContext,
    setDynamicWelcome,
    clearDynamicWelcome,
    queueMessage,
    consumePendingMessage,
    queueConversationRestore,
    consumePendingConversationId,
    consumePendingAgentId,
    markUnread,
    // Interaction confirmation / 交互确认
    queueInteractionUpdate,
    consumeInteractionUpdates,
    restoreInteractionUpdates,

    // Reset / 重置
    $reset,
  };
});
